// <auto-generated>
//     This file was generated by HawkN.Iso.Countries.Generators source generator
//     Source URL: https://unstats.un.org/unsd/methodology/m49/overview
//     Do not modify this file manually.
// </auto-generated>
#nullable enable
using System.Collections.Generic;
namespace HawkN.Iso.Countries
{
    /// <summary>
    /// Country codes ISO3166
    /// </summary>
    public static class CountryCode
    {
        /// <summary>
        /// Represents the ISO 3166-1 Alpha-2 two-letter country codes (e.g., "US", "DE").
        /// </summary>
        public enum TwoLetterCode
        {
            /// <summary>
            /// Afghanistan
            /// </summary>
            AF,
            /// <summary>
            /// Åland Islands
            /// </summary>
            AX,
            /// <summary>
            /// Albania
            /// </summary>
            AL,
            /// <summary>
            /// Algeria
            /// </summary>
            DZ,
            /// <summary>
            /// American Samoa
            /// </summary>
            AS,
            /// <summary>
            /// Andorra
            /// </summary>
            AD,
            /// <summary>
            /// Angola
            /// </summary>
            AO,
            /// <summary>
            /// Anguilla
            /// </summary>
            AI,
            /// <summary>
            /// Antarctica
            /// </summary>
            AQ,
            /// <summary>
            /// Antigua and Barbuda
            /// </summary>
            AG,
            /// <summary>
            /// Argentina
            /// </summary>
            AR,
            /// <summary>
            /// Armenia
            /// </summary>
            AM,
            /// <summary>
            /// Aruba
            /// </summary>
            AW,
            /// <summary>
            /// Australia
            /// </summary>
            AU,
            /// <summary>
            /// Austria
            /// </summary>
            AT,
            /// <summary>
            /// Azerbaijan
            /// </summary>
            AZ,
            /// <summary>
            /// Bahamas
            /// </summary>
            BS,
            /// <summary>
            /// Bahrain
            /// </summary>
            BH,
            /// <summary>
            /// Bangladesh
            /// </summary>
            BD,
            /// <summary>
            /// Barbados
            /// </summary>
            BB,
            /// <summary>
            /// Belarus
            /// </summary>
            BY,
            /// <summary>
            /// Belgium
            /// </summary>
            BE,
            /// <summary>
            /// Belize
            /// </summary>
            BZ,
            /// <summary>
            /// Benin
            /// </summary>
            BJ,
            /// <summary>
            /// Bermuda
            /// </summary>
            BM,
            /// <summary>
            /// Bhutan
            /// </summary>
            BT,
            /// <summary>
            /// Bolivia (Plurinational State of)
            /// </summary>
            BO,
            /// <summary>
            /// Bonaire, Sint Eustatius and Saba
            /// </summary>
            BQ,
            /// <summary>
            /// Bosnia and Herzegovina
            /// </summary>
            BA,
            /// <summary>
            /// Botswana
            /// </summary>
            BW,
            /// <summary>
            /// Bouvet Island
            /// </summary>
            BV,
            /// <summary>
            /// Brazil
            /// </summary>
            BR,
            /// <summary>
            /// British Indian Ocean Territory
            /// </summary>
            IO,
            /// <summary>
            /// British Virgin Islands
            /// </summary>
            VG,
            /// <summary>
            /// Brunei Darussalam
            /// </summary>
            BN,
            /// <summary>
            /// Bulgaria
            /// </summary>
            BG,
            /// <summary>
            /// Burkina Faso
            /// </summary>
            BF,
            /// <summary>
            /// Burundi
            /// </summary>
            BI,
            /// <summary>
            /// Cabo Verde
            /// </summary>
            CV,
            /// <summary>
            /// Cambodia
            /// </summary>
            KH,
            /// <summary>
            /// Cameroon
            /// </summary>
            CM,
            /// <summary>
            /// Canada
            /// </summary>
            CA,
            /// <summary>
            /// Cayman Islands
            /// </summary>
            KY,
            /// <summary>
            /// Central African Republic
            /// </summary>
            CF,
            /// <summary>
            /// Chad
            /// </summary>
            TD,
            /// <summary>
            /// Chile
            /// </summary>
            CL,
            /// <summary>
            /// China
            /// </summary>
            CN,
            /// <summary>
            /// China, Hong Kong Special Administrative Region
            /// </summary>
            HK,
            /// <summary>
            /// China, Macao Special Administrative Region
            /// </summary>
            MO,
            /// <summary>
            /// Christmas Island
            /// </summary>
            CX,
            /// <summary>
            /// Cocos (Keeling) Islands
            /// </summary>
            CC,
            /// <summary>
            /// Colombia
            /// </summary>
            CO,
            /// <summary>
            /// Comoros
            /// </summary>
            KM,
            /// <summary>
            /// Congo
            /// </summary>
            CG,
            /// <summary>
            /// Cook Islands
            /// </summary>
            CK,
            /// <summary>
            /// Costa Rica
            /// </summary>
            CR,
            /// <summary>
            /// Côte d’Ivoire
            /// </summary>
            CI,
            /// <summary>
            /// Croatia
            /// </summary>
            HR,
            /// <summary>
            /// Cuba
            /// </summary>
            CU,
            /// <summary>
            /// Curaçao
            /// </summary>
            CW,
            /// <summary>
            /// Cyprus
            /// </summary>
            CY,
            /// <summary>
            /// Czechia
            /// </summary>
            CZ,
            /// <summary>
            /// Democratic People's Republic of Korea
            /// </summary>
            KP,
            /// <summary>
            /// Democratic Republic of the Congo
            /// </summary>
            CD,
            /// <summary>
            /// Denmark
            /// </summary>
            DK,
            /// <summary>
            /// Djibouti
            /// </summary>
            DJ,
            /// <summary>
            /// Dominica
            /// </summary>
            DM,
            /// <summary>
            /// Dominican Republic
            /// </summary>
            DO,
            /// <summary>
            /// Ecuador
            /// </summary>
            EC,
            /// <summary>
            /// Egypt
            /// </summary>
            EG,
            /// <summary>
            /// El Salvador
            /// </summary>
            SV,
            /// <summary>
            /// Equatorial Guinea
            /// </summary>
            GQ,
            /// <summary>
            /// Eritrea
            /// </summary>
            ER,
            /// <summary>
            /// Estonia
            /// </summary>
            EE,
            /// <summary>
            /// Eswatini
            /// </summary>
            SZ,
            /// <summary>
            /// Ethiopia
            /// </summary>
            ET,
            /// <summary>
            /// Falkland Islands (Malvinas)
            /// </summary>
            FK,
            /// <summary>
            /// Faroe Islands
            /// </summary>
            FO,
            /// <summary>
            /// Fiji
            /// </summary>
            FJ,
            /// <summary>
            /// Finland
            /// </summary>
            FI,
            /// <summary>
            /// France
            /// </summary>
            FR,
            /// <summary>
            /// French Guiana
            /// </summary>
            GF,
            /// <summary>
            /// French Polynesia
            /// </summary>
            PF,
            /// <summary>
            /// French Southern Territories
            /// </summary>
            TF,
            /// <summary>
            /// Gabon
            /// </summary>
            GA,
            /// <summary>
            /// Gambia
            /// </summary>
            GM,
            /// <summary>
            /// Georgia
            /// </summary>
            GE,
            /// <summary>
            /// Germany
            /// </summary>
            DE,
            /// <summary>
            /// Ghana
            /// </summary>
            GH,
            /// <summary>
            /// Gibraltar
            /// </summary>
            GI,
            /// <summary>
            /// Greece
            /// </summary>
            GR,
            /// <summary>
            /// Greenland
            /// </summary>
            GL,
            /// <summary>
            /// Grenada
            /// </summary>
            GD,
            /// <summary>
            /// Guadeloupe
            /// </summary>
            GP,
            /// <summary>
            /// Guam
            /// </summary>
            GU,
            /// <summary>
            /// Guatemala
            /// </summary>
            GT,
            /// <summary>
            /// Guernsey
            /// </summary>
            GG,
            /// <summary>
            /// Guinea
            /// </summary>
            GN,
            /// <summary>
            /// Guinea-Bissau
            /// </summary>
            GW,
            /// <summary>
            /// Guyana
            /// </summary>
            GY,
            /// <summary>
            /// Haiti
            /// </summary>
            HT,
            /// <summary>
            /// Heard Island and McDonald Islands
            /// </summary>
            HM,
            /// <summary>
            /// Holy See
            /// </summary>
            VA,
            /// <summary>
            /// Honduras
            /// </summary>
            HN,
            /// <summary>
            /// Hungary
            /// </summary>
            HU,
            /// <summary>
            /// Iceland
            /// </summary>
            IS,
            /// <summary>
            /// India
            /// </summary>
            IN,
            /// <summary>
            /// Indonesia
            /// </summary>
            ID,
            /// <summary>
            /// Iran (Islamic Republic of)
            /// </summary>
            IR,
            /// <summary>
            /// Iraq
            /// </summary>
            IQ,
            /// <summary>
            /// Ireland
            /// </summary>
            IE,
            /// <summary>
            /// Isle of Man
            /// </summary>
            IM,
            /// <summary>
            /// Israel
            /// </summary>
            IL,
            /// <summary>
            /// Italy
            /// </summary>
            IT,
            /// <summary>
            /// Jamaica
            /// </summary>
            JM,
            /// <summary>
            /// Japan
            /// </summary>
            JP,
            /// <summary>
            /// Jersey
            /// </summary>
            JE,
            /// <summary>
            /// Jordan
            /// </summary>
            JO,
            /// <summary>
            /// Kazakhstan
            /// </summary>
            KZ,
            /// <summary>
            /// Kenya
            /// </summary>
            KE,
            /// <summary>
            /// Kiribati
            /// </summary>
            KI,
            /// <summary>
            /// Kuwait
            /// </summary>
            KW,
            /// <summary>
            /// Kyrgyzstan
            /// </summary>
            KG,
            /// <summary>
            /// Lao People's Democratic Republic
            /// </summary>
            LA,
            /// <summary>
            /// Latvia
            /// </summary>
            LV,
            /// <summary>
            /// Lebanon
            /// </summary>
            LB,
            /// <summary>
            /// Lesotho
            /// </summary>
            LS,
            /// <summary>
            /// Liberia
            /// </summary>
            LR,
            /// <summary>
            /// Libya
            /// </summary>
            LY,
            /// <summary>
            /// Liechtenstein
            /// </summary>
            LI,
            /// <summary>
            /// Lithuania
            /// </summary>
            LT,
            /// <summary>
            /// Luxembourg
            /// </summary>
            LU,
            /// <summary>
            /// Madagascar
            /// </summary>
            MG,
            /// <summary>
            /// Malawi
            /// </summary>
            MW,
            /// <summary>
            /// Malaysia
            /// </summary>
            MY,
            /// <summary>
            /// Maldives
            /// </summary>
            MV,
            /// <summary>
            /// Mali
            /// </summary>
            ML,
            /// <summary>
            /// Malta
            /// </summary>
            MT,
            /// <summary>
            /// Marshall Islands
            /// </summary>
            MH,
            /// <summary>
            /// Martinique
            /// </summary>
            MQ,
            /// <summary>
            /// Mauritania
            /// </summary>
            MR,
            /// <summary>
            /// Mauritius
            /// </summary>
            MU,
            /// <summary>
            /// Mayotte
            /// </summary>
            YT,
            /// <summary>
            /// Mexico
            /// </summary>
            MX,
            /// <summary>
            /// Micronesia (Federated States of)
            /// </summary>
            FM,
            /// <summary>
            /// Monaco
            /// </summary>
            MC,
            /// <summary>
            /// Mongolia
            /// </summary>
            MN,
            /// <summary>
            /// Montenegro
            /// </summary>
            ME,
            /// <summary>
            /// Montserrat
            /// </summary>
            MS,
            /// <summary>
            /// Morocco
            /// </summary>
            MA,
            /// <summary>
            /// Mozambique
            /// </summary>
            MZ,
            /// <summary>
            /// Myanmar
            /// </summary>
            MM,
            /// <summary>
            /// Namibia
            /// </summary>
            NA,
            /// <summary>
            /// Nauru
            /// </summary>
            NR,
            /// <summary>
            /// Nepal
            /// </summary>
            NP,
            /// <summary>
            /// Netherlands (Kingdom of the)
            /// </summary>
            NL,
            /// <summary>
            /// New Caledonia
            /// </summary>
            NC,
            /// <summary>
            /// New Zealand
            /// </summary>
            NZ,
            /// <summary>
            /// Nicaragua
            /// </summary>
            NI,
            /// <summary>
            /// Niger
            /// </summary>
            NE,
            /// <summary>
            /// Nigeria
            /// </summary>
            NG,
            /// <summary>
            /// Niue
            /// </summary>
            NU,
            /// <summary>
            /// Norfolk Island
            /// </summary>
            NF,
            /// <summary>
            /// North Macedonia
            /// </summary>
            MK,
            /// <summary>
            /// Northern Mariana Islands
            /// </summary>
            MP,
            /// <summary>
            /// Norway
            /// </summary>
            NO,
            /// <summary>
            /// Oman
            /// </summary>
            OM,
            /// <summary>
            /// Pakistan
            /// </summary>
            PK,
            /// <summary>
            /// Palau
            /// </summary>
            PW,
            /// <summary>
            /// Panama
            /// </summary>
            PA,
            /// <summary>
            /// Papua New Guinea
            /// </summary>
            PG,
            /// <summary>
            /// Paraguay
            /// </summary>
            PY,
            /// <summary>
            /// Peru
            /// </summary>
            PE,
            /// <summary>
            /// Philippines
            /// </summary>
            PH,
            /// <summary>
            /// Pitcairn
            /// </summary>
            PN,
            /// <summary>
            /// Poland
            /// </summary>
            PL,
            /// <summary>
            /// Portugal
            /// </summary>
            PT,
            /// <summary>
            /// Puerto Rico
            /// </summary>
            PR,
            /// <summary>
            /// Qatar
            /// </summary>
            QA,
            /// <summary>
            /// Republic of Korea
            /// </summary>
            KR,
            /// <summary>
            /// Republic of Moldova
            /// </summary>
            MD,
            /// <summary>
            /// Réunion
            /// </summary>
            RE,
            /// <summary>
            /// Romania
            /// </summary>
            RO,
            /// <summary>
            /// Russian Federation
            /// </summary>
            RU,
            /// <summary>
            /// Rwanda
            /// </summary>
            RW,
            /// <summary>
            /// Saint Barthélemy
            /// </summary>
            BL,
            /// <summary>
            /// Saint Helena
            /// </summary>
            SH,
            /// <summary>
            /// Saint Kitts and Nevis
            /// </summary>
            KN,
            /// <summary>
            /// Saint Lucia
            /// </summary>
            LC,
            /// <summary>
            /// Saint Martin (French Part)
            /// </summary>
            MF,
            /// <summary>
            /// Saint Pierre and Miquelon
            /// </summary>
            PM,
            /// <summary>
            /// Saint Vincent and the Grenadines
            /// </summary>
            VC,
            /// <summary>
            /// Samoa
            /// </summary>
            WS,
            /// <summary>
            /// San Marino
            /// </summary>
            SM,
            /// <summary>
            /// Sao Tome and Principe
            /// </summary>
            ST,
            /// <summary>
            /// Saudi Arabia
            /// </summary>
            SA,
            /// <summary>
            /// Senegal
            /// </summary>
            SN,
            /// <summary>
            /// Serbia
            /// </summary>
            RS,
            /// <summary>
            /// Seychelles
            /// </summary>
            SC,
            /// <summary>
            /// Sierra Leone
            /// </summary>
            SL,
            /// <summary>
            /// Singapore
            /// </summary>
            SG,
            /// <summary>
            /// Sint Maarten (Dutch part)
            /// </summary>
            SX,
            /// <summary>
            /// Slovakia
            /// </summary>
            SK,
            /// <summary>
            /// Slovenia
            /// </summary>
            SI,
            /// <summary>
            /// Solomon Islands
            /// </summary>
            SB,
            /// <summary>
            /// Somalia
            /// </summary>
            SO,
            /// <summary>
            /// South Africa
            /// </summary>
            ZA,
            /// <summary>
            /// South Georgia and the South Sandwich Islands
            /// </summary>
            GS,
            /// <summary>
            /// South Sudan
            /// </summary>
            SS,
            /// <summary>
            /// Spain
            /// </summary>
            ES,
            /// <summary>
            /// Sri Lanka
            /// </summary>
            LK,
            /// <summary>
            /// State of Palestine
            /// </summary>
            PS,
            /// <summary>
            /// Sudan
            /// </summary>
            SD,
            /// <summary>
            /// Suriname
            /// </summary>
            SR,
            /// <summary>
            /// Svalbard and Jan Mayen Islands
            /// </summary>
            SJ,
            /// <summary>
            /// Sweden
            /// </summary>
            SE,
            /// <summary>
            /// Switzerland
            /// </summary>
            CH,
            /// <summary>
            /// Syrian Arab Republic
            /// </summary>
            SY,
            /// <summary>
            /// Tajikistan
            /// </summary>
            TJ,
            /// <summary>
            /// Thailand
            /// </summary>
            TH,
            /// <summary>
            /// Timor-Leste
            /// </summary>
            TL,
            /// <summary>
            /// Togo
            /// </summary>
            TG,
            /// <summary>
            /// Tokelau
            /// </summary>
            TK,
            /// <summary>
            /// Tonga
            /// </summary>
            TO,
            /// <summary>
            /// Trinidad and Tobago
            /// </summary>
            TT,
            /// <summary>
            /// Tunisia
            /// </summary>
            TN,
            /// <summary>
            /// Türkiye
            /// </summary>
            TR,
            /// <summary>
            /// Turkmenistan
            /// </summary>
            TM,
            /// <summary>
            /// Turks and Caicos Islands
            /// </summary>
            TC,
            /// <summary>
            /// Tuvalu
            /// </summary>
            TV,
            /// <summary>
            /// Uganda
            /// </summary>
            UG,
            /// <summary>
            /// Ukraine
            /// </summary>
            UA,
            /// <summary>
            /// United Arab Emirates
            /// </summary>
            AE,
            /// <summary>
            /// United Kingdom of Great Britain and Northern Ireland
            /// </summary>
            GB,
            /// <summary>
            /// United Republic of Tanzania
            /// </summary>
            TZ,
            /// <summary>
            /// United States Minor Outlying Islands
            /// </summary>
            UM,
            /// <summary>
            /// United States of America
            /// </summary>
            US,
            /// <summary>
            /// United States Virgin Islands
            /// </summary>
            VI,
            /// <summary>
            /// Uruguay
            /// </summary>
            UY,
            /// <summary>
            /// Uzbekistan
            /// </summary>
            UZ,
            /// <summary>
            /// Vanuatu
            /// </summary>
            VU,
            /// <summary>
            /// Venezuela (Bolivarian Republic of)
            /// </summary>
            VE,
            /// <summary>
            /// Viet Nam
            /// </summary>
            VN,
            /// <summary>
            /// Wallis and Futuna Islands
            /// </summary>
            WF,
            /// <summary>
            /// Western Sahara
            /// </summary>
            EH,
            /// <summary>
            /// Yemen
            /// </summary>
            YE,
            /// <summary>
            /// Zambia
            /// </summary>
            ZM,
            /// <summary>
            /// Zimbabwe
            /// </summary>
            ZW,
        }
        /// <summary>
        /// Represents the ISO 3166-1 Alpha-3 three-letter country codes (e.g., "USA", "DEU").
        /// </summary>
        public enum ThreeLetterCode
        {
            /// <summary>
            /// Afghanistan
            /// </summary>
            AFG,
            /// <summary>
            /// Åland Islands
            /// </summary>
            ALA,
            /// <summary>
            /// Albania
            /// </summary>
            ALB,
            /// <summary>
            /// Algeria
            /// </summary>
            DZA,
            /// <summary>
            /// American Samoa
            /// </summary>
            ASM,
            /// <summary>
            /// Andorra
            /// </summary>
            AND,
            /// <summary>
            /// Angola
            /// </summary>
            AGO,
            /// <summary>
            /// Anguilla
            /// </summary>
            AIA,
            /// <summary>
            /// Antarctica
            /// </summary>
            ATA,
            /// <summary>
            /// Antigua and Barbuda
            /// </summary>
            ATG,
            /// <summary>
            /// Argentina
            /// </summary>
            ARG,
            /// <summary>
            /// Armenia
            /// </summary>
            ARM,
            /// <summary>
            /// Aruba
            /// </summary>
            ABW,
            /// <summary>
            /// Australia
            /// </summary>
            AUS,
            /// <summary>
            /// Austria
            /// </summary>
            AUT,
            /// <summary>
            /// Azerbaijan
            /// </summary>
            AZE,
            /// <summary>
            /// Bahamas
            /// </summary>
            BHS,
            /// <summary>
            /// Bahrain
            /// </summary>
            BHR,
            /// <summary>
            /// Bangladesh
            /// </summary>
            BGD,
            /// <summary>
            /// Barbados
            /// </summary>
            BRB,
            /// <summary>
            /// Belarus
            /// </summary>
            BLR,
            /// <summary>
            /// Belgium
            /// </summary>
            BEL,
            /// <summary>
            /// Belize
            /// </summary>
            BLZ,
            /// <summary>
            /// Benin
            /// </summary>
            BEN,
            /// <summary>
            /// Bermuda
            /// </summary>
            BMU,
            /// <summary>
            /// Bhutan
            /// </summary>
            BTN,
            /// <summary>
            /// Bolivia (Plurinational State of)
            /// </summary>
            BOL,
            /// <summary>
            /// Bonaire, Sint Eustatius and Saba
            /// </summary>
            BES,
            /// <summary>
            /// Bosnia and Herzegovina
            /// </summary>
            BIH,
            /// <summary>
            /// Botswana
            /// </summary>
            BWA,
            /// <summary>
            /// Bouvet Island
            /// </summary>
            BVT,
            /// <summary>
            /// Brazil
            /// </summary>
            BRA,
            /// <summary>
            /// British Indian Ocean Territory
            /// </summary>
            IOT,
            /// <summary>
            /// British Virgin Islands
            /// </summary>
            VGB,
            /// <summary>
            /// Brunei Darussalam
            /// </summary>
            BRN,
            /// <summary>
            /// Bulgaria
            /// </summary>
            BGR,
            /// <summary>
            /// Burkina Faso
            /// </summary>
            BFA,
            /// <summary>
            /// Burundi
            /// </summary>
            BDI,
            /// <summary>
            /// Cabo Verde
            /// </summary>
            CPV,
            /// <summary>
            /// Cambodia
            /// </summary>
            KHM,
            /// <summary>
            /// Cameroon
            /// </summary>
            CMR,
            /// <summary>
            /// Canada
            /// </summary>
            CAN,
            /// <summary>
            /// Cayman Islands
            /// </summary>
            CYM,
            /// <summary>
            /// Central African Republic
            /// </summary>
            CAF,
            /// <summary>
            /// Chad
            /// </summary>
            TCD,
            /// <summary>
            /// Chile
            /// </summary>
            CHL,
            /// <summary>
            /// China
            /// </summary>
            CHN,
            /// <summary>
            /// China, Hong Kong Special Administrative Region
            /// </summary>
            HKG,
            /// <summary>
            /// China, Macao Special Administrative Region
            /// </summary>
            MAC,
            /// <summary>
            /// Christmas Island
            /// </summary>
            CXR,
            /// <summary>
            /// Cocos (Keeling) Islands
            /// </summary>
            CCK,
            /// <summary>
            /// Colombia
            /// </summary>
            COL,
            /// <summary>
            /// Comoros
            /// </summary>
            COM,
            /// <summary>
            /// Congo
            /// </summary>
            COG,
            /// <summary>
            /// Cook Islands
            /// </summary>
            COK,
            /// <summary>
            /// Costa Rica
            /// </summary>
            CRI,
            /// <summary>
            /// Côte d’Ivoire
            /// </summary>
            CIV,
            /// <summary>
            /// Croatia
            /// </summary>
            HRV,
            /// <summary>
            /// Cuba
            /// </summary>
            CUB,
            /// <summary>
            /// Curaçao
            /// </summary>
            CUW,
            /// <summary>
            /// Cyprus
            /// </summary>
            CYP,
            /// <summary>
            /// Czechia
            /// </summary>
            CZE,
            /// <summary>
            /// Democratic People's Republic of Korea
            /// </summary>
            PRK,
            /// <summary>
            /// Democratic Republic of the Congo
            /// </summary>
            COD,
            /// <summary>
            /// Denmark
            /// </summary>
            DNK,
            /// <summary>
            /// Djibouti
            /// </summary>
            DJI,
            /// <summary>
            /// Dominica
            /// </summary>
            DMA,
            /// <summary>
            /// Dominican Republic
            /// </summary>
            DOM,
            /// <summary>
            /// Ecuador
            /// </summary>
            ECU,
            /// <summary>
            /// Egypt
            /// </summary>
            EGY,
            /// <summary>
            /// El Salvador
            /// </summary>
            SLV,
            /// <summary>
            /// Equatorial Guinea
            /// </summary>
            GNQ,
            /// <summary>
            /// Eritrea
            /// </summary>
            ERI,
            /// <summary>
            /// Estonia
            /// </summary>
            EST,
            /// <summary>
            /// Eswatini
            /// </summary>
            SWZ,
            /// <summary>
            /// Ethiopia
            /// </summary>
            ETH,
            /// <summary>
            /// Falkland Islands (Malvinas)
            /// </summary>
            FLK,
            /// <summary>
            /// Faroe Islands
            /// </summary>
            FRO,
            /// <summary>
            /// Fiji
            /// </summary>
            FJI,
            /// <summary>
            /// Finland
            /// </summary>
            FIN,
            /// <summary>
            /// France
            /// </summary>
            FRA,
            /// <summary>
            /// French Guiana
            /// </summary>
            GUF,
            /// <summary>
            /// French Polynesia
            /// </summary>
            PYF,
            /// <summary>
            /// French Southern Territories
            /// </summary>
            ATF,
            /// <summary>
            /// Gabon
            /// </summary>
            GAB,
            /// <summary>
            /// Gambia
            /// </summary>
            GMB,
            /// <summary>
            /// Georgia
            /// </summary>
            GEO,
            /// <summary>
            /// Germany
            /// </summary>
            DEU,
            /// <summary>
            /// Ghana
            /// </summary>
            GHA,
            /// <summary>
            /// Gibraltar
            /// </summary>
            GIB,
            /// <summary>
            /// Greece
            /// </summary>
            GRC,
            /// <summary>
            /// Greenland
            /// </summary>
            GRL,
            /// <summary>
            /// Grenada
            /// </summary>
            GRD,
            /// <summary>
            /// Guadeloupe
            /// </summary>
            GLP,
            /// <summary>
            /// Guam
            /// </summary>
            GUM,
            /// <summary>
            /// Guatemala
            /// </summary>
            GTM,
            /// <summary>
            /// Guernsey
            /// </summary>
            GGY,
            /// <summary>
            /// Guinea
            /// </summary>
            GIN,
            /// <summary>
            /// Guinea-Bissau
            /// </summary>
            GNB,
            /// <summary>
            /// Guyana
            /// </summary>
            GUY,
            /// <summary>
            /// Haiti
            /// </summary>
            HTI,
            /// <summary>
            /// Heard Island and McDonald Islands
            /// </summary>
            HMD,
            /// <summary>
            /// Holy See
            /// </summary>
            VAT,
            /// <summary>
            /// Honduras
            /// </summary>
            HND,
            /// <summary>
            /// Hungary
            /// </summary>
            HUN,
            /// <summary>
            /// Iceland
            /// </summary>
            ISL,
            /// <summary>
            /// India
            /// </summary>
            IND,
            /// <summary>
            /// Indonesia
            /// </summary>
            IDN,
            /// <summary>
            /// Iran (Islamic Republic of)
            /// </summary>
            IRN,
            /// <summary>
            /// Iraq
            /// </summary>
            IRQ,
            /// <summary>
            /// Ireland
            /// </summary>
            IRL,
            /// <summary>
            /// Isle of Man
            /// </summary>
            IMN,
            /// <summary>
            /// Israel
            /// </summary>
            ISR,
            /// <summary>
            /// Italy
            /// </summary>
            ITA,
            /// <summary>
            /// Jamaica
            /// </summary>
            JAM,
            /// <summary>
            /// Japan
            /// </summary>
            JPN,
            /// <summary>
            /// Jersey
            /// </summary>
            JEY,
            /// <summary>
            /// Jordan
            /// </summary>
            JOR,
            /// <summary>
            /// Kazakhstan
            /// </summary>
            KAZ,
            /// <summary>
            /// Kenya
            /// </summary>
            KEN,
            /// <summary>
            /// Kiribati
            /// </summary>
            KIR,
            /// <summary>
            /// Kuwait
            /// </summary>
            KWT,
            /// <summary>
            /// Kyrgyzstan
            /// </summary>
            KGZ,
            /// <summary>
            /// Lao People's Democratic Republic
            /// </summary>
            LAO,
            /// <summary>
            /// Latvia
            /// </summary>
            LVA,
            /// <summary>
            /// Lebanon
            /// </summary>
            LBN,
            /// <summary>
            /// Lesotho
            /// </summary>
            LSO,
            /// <summary>
            /// Liberia
            /// </summary>
            LBR,
            /// <summary>
            /// Libya
            /// </summary>
            LBY,
            /// <summary>
            /// Liechtenstein
            /// </summary>
            LIE,
            /// <summary>
            /// Lithuania
            /// </summary>
            LTU,
            /// <summary>
            /// Luxembourg
            /// </summary>
            LUX,
            /// <summary>
            /// Madagascar
            /// </summary>
            MDG,
            /// <summary>
            /// Malawi
            /// </summary>
            MWI,
            /// <summary>
            /// Malaysia
            /// </summary>
            MYS,
            /// <summary>
            /// Maldives
            /// </summary>
            MDV,
            /// <summary>
            /// Mali
            /// </summary>
            MLI,
            /// <summary>
            /// Malta
            /// </summary>
            MLT,
            /// <summary>
            /// Marshall Islands
            /// </summary>
            MHL,
            /// <summary>
            /// Martinique
            /// </summary>
            MTQ,
            /// <summary>
            /// Mauritania
            /// </summary>
            MRT,
            /// <summary>
            /// Mauritius
            /// </summary>
            MUS,
            /// <summary>
            /// Mayotte
            /// </summary>
            MYT,
            /// <summary>
            /// Mexico
            /// </summary>
            MEX,
            /// <summary>
            /// Micronesia (Federated States of)
            /// </summary>
            FSM,
            /// <summary>
            /// Monaco
            /// </summary>
            MCO,
            /// <summary>
            /// Mongolia
            /// </summary>
            MNG,
            /// <summary>
            /// Montenegro
            /// </summary>
            MNE,
            /// <summary>
            /// Montserrat
            /// </summary>
            MSR,
            /// <summary>
            /// Morocco
            /// </summary>
            MAR,
            /// <summary>
            /// Mozambique
            /// </summary>
            MOZ,
            /// <summary>
            /// Myanmar
            /// </summary>
            MMR,
            /// <summary>
            /// Namibia
            /// </summary>
            NAM,
            /// <summary>
            /// Nauru
            /// </summary>
            NRU,
            /// <summary>
            /// Nepal
            /// </summary>
            NPL,
            /// <summary>
            /// Netherlands (Kingdom of the)
            /// </summary>
            NLD,
            /// <summary>
            /// New Caledonia
            /// </summary>
            NCL,
            /// <summary>
            /// New Zealand
            /// </summary>
            NZL,
            /// <summary>
            /// Nicaragua
            /// </summary>
            NIC,
            /// <summary>
            /// Niger
            /// </summary>
            NER,
            /// <summary>
            /// Nigeria
            /// </summary>
            NGA,
            /// <summary>
            /// Niue
            /// </summary>
            NIU,
            /// <summary>
            /// Norfolk Island
            /// </summary>
            NFK,
            /// <summary>
            /// North Macedonia
            /// </summary>
            MKD,
            /// <summary>
            /// Northern Mariana Islands
            /// </summary>
            MNP,
            /// <summary>
            /// Norway
            /// </summary>
            NOR,
            /// <summary>
            /// Oman
            /// </summary>
            OMN,
            /// <summary>
            /// Pakistan
            /// </summary>
            PAK,
            /// <summary>
            /// Palau
            /// </summary>
            PLW,
            /// <summary>
            /// Panama
            /// </summary>
            PAN,
            /// <summary>
            /// Papua New Guinea
            /// </summary>
            PNG,
            /// <summary>
            /// Paraguay
            /// </summary>
            PRY,
            /// <summary>
            /// Peru
            /// </summary>
            PER,
            /// <summary>
            /// Philippines
            /// </summary>
            PHL,
            /// <summary>
            /// Pitcairn
            /// </summary>
            PCN,
            /// <summary>
            /// Poland
            /// </summary>
            POL,
            /// <summary>
            /// Portugal
            /// </summary>
            PRT,
            /// <summary>
            /// Puerto Rico
            /// </summary>
            PRI,
            /// <summary>
            /// Qatar
            /// </summary>
            QAT,
            /// <summary>
            /// Republic of Korea
            /// </summary>
            KOR,
            /// <summary>
            /// Republic of Moldova
            /// </summary>
            MDA,
            /// <summary>
            /// Réunion
            /// </summary>
            REU,
            /// <summary>
            /// Romania
            /// </summary>
            ROU,
            /// <summary>
            /// Russian Federation
            /// </summary>
            RUS,
            /// <summary>
            /// Rwanda
            /// </summary>
            RWA,
            /// <summary>
            /// Saint Barthélemy
            /// </summary>
            BLM,
            /// <summary>
            /// Saint Helena
            /// </summary>
            SHN,
            /// <summary>
            /// Saint Kitts and Nevis
            /// </summary>
            KNA,
            /// <summary>
            /// Saint Lucia
            /// </summary>
            LCA,
            /// <summary>
            /// Saint Martin (French Part)
            /// </summary>
            MAF,
            /// <summary>
            /// Saint Pierre and Miquelon
            /// </summary>
            SPM,
            /// <summary>
            /// Saint Vincent and the Grenadines
            /// </summary>
            VCT,
            /// <summary>
            /// Samoa
            /// </summary>
            WSM,
            /// <summary>
            /// San Marino
            /// </summary>
            SMR,
            /// <summary>
            /// Sao Tome and Principe
            /// </summary>
            STP,
            /// <summary>
            /// Saudi Arabia
            /// </summary>
            SAU,
            /// <summary>
            /// Senegal
            /// </summary>
            SEN,
            /// <summary>
            /// Serbia
            /// </summary>
            SRB,
            /// <summary>
            /// Seychelles
            /// </summary>
            SYC,
            /// <summary>
            /// Sierra Leone
            /// </summary>
            SLE,
            /// <summary>
            /// Singapore
            /// </summary>
            SGP,
            /// <summary>
            /// Sint Maarten (Dutch part)
            /// </summary>
            SXM,
            /// <summary>
            /// Slovakia
            /// </summary>
            SVK,
            /// <summary>
            /// Slovenia
            /// </summary>
            SVN,
            /// <summary>
            /// Solomon Islands
            /// </summary>
            SLB,
            /// <summary>
            /// Somalia
            /// </summary>
            SOM,
            /// <summary>
            /// South Africa
            /// </summary>
            ZAF,
            /// <summary>
            /// South Georgia and the South Sandwich Islands
            /// </summary>
            SGS,
            /// <summary>
            /// South Sudan
            /// </summary>
            SSD,
            /// <summary>
            /// Spain
            /// </summary>
            ESP,
            /// <summary>
            /// Sri Lanka
            /// </summary>
            LKA,
            /// <summary>
            /// State of Palestine
            /// </summary>
            PSE,
            /// <summary>
            /// Sudan
            /// </summary>
            SDN,
            /// <summary>
            /// Suriname
            /// </summary>
            SUR,
            /// <summary>
            /// Svalbard and Jan Mayen Islands
            /// </summary>
            SJM,
            /// <summary>
            /// Sweden
            /// </summary>
            SWE,
            /// <summary>
            /// Switzerland
            /// </summary>
            CHE,
            /// <summary>
            /// Syrian Arab Republic
            /// </summary>
            SYR,
            /// <summary>
            /// Tajikistan
            /// </summary>
            TJK,
            /// <summary>
            /// Thailand
            /// </summary>
            THA,
            /// <summary>
            /// Timor-Leste
            /// </summary>
            TLS,
            /// <summary>
            /// Togo
            /// </summary>
            TGO,
            /// <summary>
            /// Tokelau
            /// </summary>
            TKL,
            /// <summary>
            /// Tonga
            /// </summary>
            TON,
            /// <summary>
            /// Trinidad and Tobago
            /// </summary>
            TTO,
            /// <summary>
            /// Tunisia
            /// </summary>
            TUN,
            /// <summary>
            /// Türkiye
            /// </summary>
            TUR,
            /// <summary>
            /// Turkmenistan
            /// </summary>
            TKM,
            /// <summary>
            /// Turks and Caicos Islands
            /// </summary>
            TCA,
            /// <summary>
            /// Tuvalu
            /// </summary>
            TUV,
            /// <summary>
            /// Uganda
            /// </summary>
            UGA,
            /// <summary>
            /// Ukraine
            /// </summary>
            UKR,
            /// <summary>
            /// United Arab Emirates
            /// </summary>
            ARE,
            /// <summary>
            /// United Kingdom of Great Britain and Northern Ireland
            /// </summary>
            GBR,
            /// <summary>
            /// United Republic of Tanzania
            /// </summary>
            TZA,
            /// <summary>
            /// United States Minor Outlying Islands
            /// </summary>
            UMI,
            /// <summary>
            /// United States of America
            /// </summary>
            USA,
            /// <summary>
            /// United States Virgin Islands
            /// </summary>
            VIR,
            /// <summary>
            /// Uruguay
            /// </summary>
            URY,
            /// <summary>
            /// Uzbekistan
            /// </summary>
            UZB,
            /// <summary>
            /// Vanuatu
            /// </summary>
            VUT,
            /// <summary>
            /// Venezuela (Bolivarian Republic of)
            /// </summary>
            VEN,
            /// <summary>
            /// Viet Nam
            /// </summary>
            VNM,
            /// <summary>
            /// Wallis and Futuna Islands
            /// </summary>
            WLF,
            /// <summary>
            /// Western Sahara
            /// </summary>
            ESH,
            /// <summary>
            /// Yemen
            /// </summary>
            YEM,
            /// <summary>
            /// Zambia
            /// </summary>
            ZMB,
            /// <summary>
            /// Zimbabwe
            /// </summary>
            ZWE,
        }
    }
}
