// <auto-generated>
//     This file was generated by HawkN.Iso.Countries.Generators source generator
//     Data Source: iso-codes project (Debian Salsa)
//     License: GNU Lesser General Public License v2.1
//     Source URL: https://salsa.debian.org/iso-codes-team/iso-codes
//     Do not modify this file manually.
// </auto-generated>
#nullable enable
using System.Collections.Generic;
namespace HawkN.Iso.Countries
{
    /// <summary>
    /// Country codes ISO3166
    /// </summary>
    public static class CountryCode
    {
        /// <summary>
        /// Represents the ISO 3166-1 Alpha-2 two-letter country codes (e.g., "US", "DE").
        /// </summary>
        public enum TwoLetterCode
        {
            /// <summary>
            /// Afghanistan (Islamic Republic of Afghanistan)
            /// </summary>
            AF,
            /// <summary>
            /// Åland Islands
            /// </summary>
            AX,
            /// <summary>
            /// Albania (Republic of Albania)
            /// </summary>
            AL,
            /// <summary>
            /// Algeria (People's Democratic Republic of Algeria)
            /// </summary>
            DZ,
            /// <summary>
            /// American Samoa
            /// </summary>
            AS,
            /// <summary>
            /// Andorra (Principality of Andorra)
            /// </summary>
            AD,
            /// <summary>
            /// Angola (Republic of Angola)
            /// </summary>
            AO,
            /// <summary>
            /// Anguilla
            /// </summary>
            AI,
            /// <summary>
            /// Antarctica
            /// </summary>
            AQ,
            /// <summary>
            /// Antigua and Barbuda
            /// </summary>
            AG,
            /// <summary>
            /// Argentina (Argentine Republic)
            /// </summary>
            AR,
            /// <summary>
            /// Armenia (Republic of Armenia)
            /// </summary>
            AM,
            /// <summary>
            /// Aruba
            /// </summary>
            AW,
            /// <summary>
            /// Australia
            /// </summary>
            AU,
            /// <summary>
            /// Austria (Republic of Austria)
            /// </summary>
            AT,
            /// <summary>
            /// Azerbaijan (Republic of Azerbaijan)
            /// </summary>
            AZ,
            /// <summary>
            /// Bahamas (Commonwealth of the Bahamas)
            /// </summary>
            BS,
            /// <summary>
            /// Bahrain (Kingdom of Bahrain)
            /// </summary>
            BH,
            /// <summary>
            /// Bangladesh (People's Republic of Bangladesh)
            /// </summary>
            BD,
            /// <summary>
            /// Barbados
            /// </summary>
            BB,
            /// <summary>
            /// Belarus (Republic of Belarus)
            /// </summary>
            BY,
            /// <summary>
            /// Belgium (Kingdom of Belgium)
            /// </summary>
            BE,
            /// <summary>
            /// Belize
            /// </summary>
            BZ,
            /// <summary>
            /// Benin (Republic of Benin)
            /// </summary>
            BJ,
            /// <summary>
            /// Bermuda
            /// </summary>
            BM,
            /// <summary>
            /// Bhutan (Kingdom of Bhutan)
            /// </summary>
            BT,
            /// <summary>
            /// Bolivia, Plurinational State of (Plurinational State of Bolivia)
            /// </summary>
            BO,
            /// <summary>
            /// Bonaire, Sint Eustatius and Saba (Bonaire, Sint Eustatius and Saba)
            /// </summary>
            BQ,
            /// <summary>
            /// Bosnia and Herzegovina (Republic of Bosnia and Herzegovina)
            /// </summary>
            BA,
            /// <summary>
            /// Botswana (Republic of Botswana)
            /// </summary>
            BW,
            /// <summary>
            /// Bouvet Island
            /// </summary>
            BV,
            /// <summary>
            /// Brazil (Federative Republic of Brazil)
            /// </summary>
            BR,
            /// <summary>
            /// British Indian Ocean Territory
            /// </summary>
            IO,
            /// <summary>
            /// Brunei Darussalam
            /// </summary>
            BN,
            /// <summary>
            /// Bulgaria (Republic of Bulgaria)
            /// </summary>
            BG,
            /// <summary>
            /// Burkina Faso
            /// </summary>
            BF,
            /// <summary>
            /// Burundi (Republic of Burundi)
            /// </summary>
            BI,
            /// <summary>
            /// Cabo Verde (Republic of Cabo Verde)
            /// </summary>
            CV,
            /// <summary>
            /// Cambodia (Kingdom of Cambodia)
            /// </summary>
            KH,
            /// <summary>
            /// Cameroon (Republic of Cameroon)
            /// </summary>
            CM,
            /// <summary>
            /// Canada
            /// </summary>
            CA,
            /// <summary>
            /// Cayman Islands
            /// </summary>
            KY,
            /// <summary>
            /// Central African Republic
            /// </summary>
            CF,
            /// <summary>
            /// Chad (Republic of Chad)
            /// </summary>
            TD,
            /// <summary>
            /// Chile (Republic of Chile)
            /// </summary>
            CL,
            /// <summary>
            /// China (People's Republic of China)
            /// </summary>
            CN,
            /// <summary>
            /// Christmas Island
            /// </summary>
            CX,
            /// <summary>
            /// Cocos (Keeling) Islands
            /// </summary>
            CC,
            /// <summary>
            /// Colombia (Republic of Colombia)
            /// </summary>
            CO,
            /// <summary>
            /// Comoros (Union of the Comoros)
            /// </summary>
            KM,
            /// <summary>
            /// Congo (Republic of the Congo)
            /// </summary>
            CG,
            /// <summary>
            /// Congo, The Democratic Republic of the
            /// </summary>
            CD,
            /// <summary>
            /// Cook Islands
            /// </summary>
            CK,
            /// <summary>
            /// Costa Rica (Republic of Costa Rica)
            /// </summary>
            CR,
            /// <summary>
            /// Côte d'Ivoire (Republic of Côte d'Ivoire)
            /// </summary>
            CI,
            /// <summary>
            /// Croatia (Republic of Croatia)
            /// </summary>
            HR,
            /// <summary>
            /// Cuba (Republic of Cuba)
            /// </summary>
            CU,
            /// <summary>
            /// Curaçao (Curaçao)
            /// </summary>
            CW,
            /// <summary>
            /// Cyprus (Republic of Cyprus)
            /// </summary>
            CY,
            /// <summary>
            /// Czechia (Czech Republic)
            /// </summary>
            CZ,
            /// <summary>
            /// Denmark (Kingdom of Denmark)
            /// </summary>
            DK,
            /// <summary>
            /// Djibouti (Republic of Djibouti)
            /// </summary>
            DJ,
            /// <summary>
            /// Dominica (Commonwealth of Dominica)
            /// </summary>
            DM,
            /// <summary>
            /// Dominican Republic
            /// </summary>
            DO,
            /// <summary>
            /// Ecuador (Republic of Ecuador)
            /// </summary>
            EC,
            /// <summary>
            /// Egypt (Arab Republic of Egypt)
            /// </summary>
            EG,
            /// <summary>
            /// El Salvador (Republic of El Salvador)
            /// </summary>
            SV,
            /// <summary>
            /// Equatorial Guinea (Republic of Equatorial Guinea)
            /// </summary>
            GQ,
            /// <summary>
            /// Eritrea (the State of Eritrea)
            /// </summary>
            ER,
            /// <summary>
            /// Estonia (Republic of Estonia)
            /// </summary>
            EE,
            /// <summary>
            /// Eswatini (Kingdom of Eswatini)
            /// </summary>
            SZ,
            /// <summary>
            /// Ethiopia (Federal Democratic Republic of Ethiopia)
            /// </summary>
            ET,
            /// <summary>
            /// Falkland Islands (Malvinas)
            /// </summary>
            FK,
            /// <summary>
            /// Faroe Islands
            /// </summary>
            FO,
            /// <summary>
            /// Fiji (Republic of Fiji)
            /// </summary>
            FJ,
            /// <summary>
            /// Finland (Republic of Finland)
            /// </summary>
            FI,
            /// <summary>
            /// France (French Republic)
            /// </summary>
            FR,
            /// <summary>
            /// French Guiana
            /// </summary>
            GF,
            /// <summary>
            /// French Polynesia
            /// </summary>
            PF,
            /// <summary>
            /// French Southern Territories
            /// </summary>
            TF,
            /// <summary>
            /// Gabon (Gabonese Republic)
            /// </summary>
            GA,
            /// <summary>
            /// Gambia (Republic of the Gambia)
            /// </summary>
            GM,
            /// <summary>
            /// Georgia
            /// </summary>
            GE,
            /// <summary>
            /// Germany (Federal Republic of Germany)
            /// </summary>
            DE,
            /// <summary>
            /// Ghana (Republic of Ghana)
            /// </summary>
            GH,
            /// <summary>
            /// Gibraltar
            /// </summary>
            GI,
            /// <summary>
            /// Greece (Hellenic Republic)
            /// </summary>
            GR,
            /// <summary>
            /// Greenland
            /// </summary>
            GL,
            /// <summary>
            /// Grenada
            /// </summary>
            GD,
            /// <summary>
            /// Guadeloupe
            /// </summary>
            GP,
            /// <summary>
            /// Guam
            /// </summary>
            GU,
            /// <summary>
            /// Guatemala (Republic of Guatemala)
            /// </summary>
            GT,
            /// <summary>
            /// Guernsey
            /// </summary>
            GG,
            /// <summary>
            /// Guinea (Republic of Guinea)
            /// </summary>
            GN,
            /// <summary>
            /// Guinea-Bissau (Republic of Guinea-Bissau)
            /// </summary>
            GW,
            /// <summary>
            /// Guyana (Republic of Guyana)
            /// </summary>
            GY,
            /// <summary>
            /// Haiti (Republic of Haiti)
            /// </summary>
            HT,
            /// <summary>
            /// Heard Island and McDonald Islands
            /// </summary>
            HM,
            /// <summary>
            /// Holy See (Vatican City State)
            /// </summary>
            VA,
            /// <summary>
            /// Honduras (Republic of Honduras)
            /// </summary>
            HN,
            /// <summary>
            /// Hong Kong (Hong Kong Special Administrative Region of China)
            /// </summary>
            HK,
            /// <summary>
            /// Hungary (Hungary)
            /// </summary>
            HU,
            /// <summary>
            /// Iceland (Republic of Iceland)
            /// </summary>
            IS,
            /// <summary>
            /// India (Republic of India)
            /// </summary>
            IN,
            /// <summary>
            /// Indonesia (Republic of Indonesia)
            /// </summary>
            ID,
            /// <summary>
            /// Iran, Islamic Republic of (Islamic Republic of Iran)
            /// </summary>
            IR,
            /// <summary>
            /// Iraq (Republic of Iraq)
            /// </summary>
            IQ,
            /// <summary>
            /// Ireland
            /// </summary>
            IE,
            /// <summary>
            /// Isle of Man
            /// </summary>
            IM,
            /// <summary>
            /// Israel (State of Israel)
            /// </summary>
            IL,
            /// <summary>
            /// Italy (Italian Republic)
            /// </summary>
            IT,
            /// <summary>
            /// Jamaica
            /// </summary>
            JM,
            /// <summary>
            /// Japan
            /// </summary>
            JP,
            /// <summary>
            /// Jersey
            /// </summary>
            JE,
            /// <summary>
            /// Jordan (Hashemite Kingdom of Jordan)
            /// </summary>
            JO,
            /// <summary>
            /// Kazakhstan (Republic of Kazakhstan)
            /// </summary>
            KZ,
            /// <summary>
            /// Kenya (Republic of Kenya)
            /// </summary>
            KE,
            /// <summary>
            /// Kiribati (Republic of Kiribati)
            /// </summary>
            KI,
            /// <summary>
            /// Korea, Democratic People's Republic of (Democratic People's Republic of Korea)
            /// </summary>
            KP,
            /// <summary>
            /// Korea, Republic of
            /// </summary>
            KR,
            /// <summary>
            /// Kuwait (State of Kuwait)
            /// </summary>
            KW,
            /// <summary>
            /// Kyrgyzstan (Kyrgyz Republic)
            /// </summary>
            KG,
            /// <summary>
            /// Lao People's Democratic Republic
            /// </summary>
            LA,
            /// <summary>
            /// Latvia (Republic of Latvia)
            /// </summary>
            LV,
            /// <summary>
            /// Lebanon (Lebanese Republic)
            /// </summary>
            LB,
            /// <summary>
            /// Lesotho (Kingdom of Lesotho)
            /// </summary>
            LS,
            /// <summary>
            /// Liberia (Republic of Liberia)
            /// </summary>
            LR,
            /// <summary>
            /// Libya (Libya)
            /// </summary>
            LY,
            /// <summary>
            /// Liechtenstein (Principality of Liechtenstein)
            /// </summary>
            LI,
            /// <summary>
            /// Lithuania (Republic of Lithuania)
            /// </summary>
            LT,
            /// <summary>
            /// Luxembourg (Grand Duchy of Luxembourg)
            /// </summary>
            LU,
            /// <summary>
            /// Macao (Macao Special Administrative Region of China)
            /// </summary>
            MO,
            /// <summary>
            /// Madagascar (Republic of Madagascar)
            /// </summary>
            MG,
            /// <summary>
            /// Malawi (Republic of Malawi)
            /// </summary>
            MW,
            /// <summary>
            /// Malaysia
            /// </summary>
            MY,
            /// <summary>
            /// Maldives (Republic of Maldives)
            /// </summary>
            MV,
            /// <summary>
            /// Mali (Republic of Mali)
            /// </summary>
            ML,
            /// <summary>
            /// Malta (Republic of Malta)
            /// </summary>
            MT,
            /// <summary>
            /// Marshall Islands (Republic of the Marshall Islands)
            /// </summary>
            MH,
            /// <summary>
            /// Martinique
            /// </summary>
            MQ,
            /// <summary>
            /// Mauritania (Islamic Republic of Mauritania)
            /// </summary>
            MR,
            /// <summary>
            /// Mauritius (Republic of Mauritius)
            /// </summary>
            MU,
            /// <summary>
            /// Mayotte
            /// </summary>
            YT,
            /// <summary>
            /// Mexico (United Mexican States)
            /// </summary>
            MX,
            /// <summary>
            /// Micronesia, Federated States of (Federated States of Micronesia)
            /// </summary>
            FM,
            /// <summary>
            /// Moldova, Republic of (Republic of Moldova)
            /// </summary>
            MD,
            /// <summary>
            /// Monaco (Principality of Monaco)
            /// </summary>
            MC,
            /// <summary>
            /// Mongolia
            /// </summary>
            MN,
            /// <summary>
            /// Montenegro (Montenegro)
            /// </summary>
            ME,
            /// <summary>
            /// Montserrat
            /// </summary>
            MS,
            /// <summary>
            /// Morocco (Kingdom of Morocco)
            /// </summary>
            MA,
            /// <summary>
            /// Mozambique (Republic of Mozambique)
            /// </summary>
            MZ,
            /// <summary>
            /// Myanmar (Republic of Myanmar)
            /// </summary>
            MM,
            /// <summary>
            /// Namibia (Republic of Namibia)
            /// </summary>
            NA,
            /// <summary>
            /// Nauru (Republic of Nauru)
            /// </summary>
            NR,
            /// <summary>
            /// Nepal (Federal Democratic Republic of Nepal)
            /// </summary>
            NP,
            /// <summary>
            /// Netherlands (Kingdom of the Netherlands)
            /// </summary>
            NL,
            /// <summary>
            /// New Caledonia
            /// </summary>
            NC,
            /// <summary>
            /// New Zealand
            /// </summary>
            NZ,
            /// <summary>
            /// Nicaragua (Republic of Nicaragua)
            /// </summary>
            NI,
            /// <summary>
            /// Niger (Republic of the Niger)
            /// </summary>
            NE,
            /// <summary>
            /// Nigeria (Federal Republic of Nigeria)
            /// </summary>
            NG,
            /// <summary>
            /// Niue (Niue)
            /// </summary>
            NU,
            /// <summary>
            /// Norfolk Island
            /// </summary>
            NF,
            /// <summary>
            /// North Macedonia (Republic of North Macedonia)
            /// </summary>
            MK,
            /// <summary>
            /// Northern Mariana Islands (Commonwealth of the Northern Mariana Islands)
            /// </summary>
            MP,
            /// <summary>
            /// Norway (Kingdom of Norway)
            /// </summary>
            NO,
            /// <summary>
            /// Oman (Sultanate of Oman)
            /// </summary>
            OM,
            /// <summary>
            /// Pakistan (Islamic Republic of Pakistan)
            /// </summary>
            PK,
            /// <summary>
            /// Palau (Republic of Palau)
            /// </summary>
            PW,
            /// <summary>
            /// Palestine, State of (the State of Palestine)
            /// </summary>
            PS,
            /// <summary>
            /// Panama (Republic of Panama)
            /// </summary>
            PA,
            /// <summary>
            /// Papua New Guinea (Independent State of Papua New Guinea)
            /// </summary>
            PG,
            /// <summary>
            /// Paraguay (Republic of Paraguay)
            /// </summary>
            PY,
            /// <summary>
            /// Peru (Republic of Peru)
            /// </summary>
            PE,
            /// <summary>
            /// Philippines (Republic of the Philippines)
            /// </summary>
            PH,
            /// <summary>
            /// Pitcairn
            /// </summary>
            PN,
            /// <summary>
            /// Poland (Republic of Poland)
            /// </summary>
            PL,
            /// <summary>
            /// Portugal (Portuguese Republic)
            /// </summary>
            PT,
            /// <summary>
            /// Puerto Rico
            /// </summary>
            PR,
            /// <summary>
            /// Qatar (State of Qatar)
            /// </summary>
            QA,
            /// <summary>
            /// Réunion
            /// </summary>
            RE,
            /// <summary>
            /// Romania
            /// </summary>
            RO,
            /// <summary>
            /// Russian Federation
            /// </summary>
            RU,
            /// <summary>
            /// Rwanda (Rwandese Republic)
            /// </summary>
            RW,
            /// <summary>
            /// Saint Barthélemy
            /// </summary>
            BL,
            /// <summary>
            /// Saint Helena, Ascension and Tristan da Cunha
            /// </summary>
            SH,
            /// <summary>
            /// Saint Kitts and Nevis
            /// </summary>
            KN,
            /// <summary>
            /// Saint Lucia
            /// </summary>
            LC,
            /// <summary>
            /// Saint Martin (French part)
            /// </summary>
            MF,
            /// <summary>
            /// Saint Pierre and Miquelon
            /// </summary>
            PM,
            /// <summary>
            /// Saint Vincent and the Grenadines
            /// </summary>
            VC,
            /// <summary>
            /// Samoa (Independent State of Samoa)
            /// </summary>
            WS,
            /// <summary>
            /// San Marino (Republic of San Marino)
            /// </summary>
            SM,
            /// <summary>
            /// Sao Tome and Principe (Democratic Republic of Sao Tome and Principe)
            /// </summary>
            ST,
            /// <summary>
            /// Saudi Arabia (Kingdom of Saudi Arabia)
            /// </summary>
            SA,
            /// <summary>
            /// Senegal (Republic of Senegal)
            /// </summary>
            SN,
            /// <summary>
            /// Serbia (Republic of Serbia)
            /// </summary>
            RS,
            /// <summary>
            /// Seychelles (Republic of Seychelles)
            /// </summary>
            SC,
            /// <summary>
            /// Sierra Leone (Republic of Sierra Leone)
            /// </summary>
            SL,
            /// <summary>
            /// Singapore (Republic of Singapore)
            /// </summary>
            SG,
            /// <summary>
            /// Sint Maarten (Dutch part) (Sint Maarten (Dutch part))
            /// </summary>
            SX,
            /// <summary>
            /// Slovakia (Slovak Republic)
            /// </summary>
            SK,
            /// <summary>
            /// Slovenia (Republic of Slovenia)
            /// </summary>
            SI,
            /// <summary>
            /// Solomon Islands
            /// </summary>
            SB,
            /// <summary>
            /// Somalia (Federal Republic of Somalia)
            /// </summary>
            SO,
            /// <summary>
            /// South Africa (Republic of South Africa)
            /// </summary>
            ZA,
            /// <summary>
            /// South Georgia and the South Sandwich Islands
            /// </summary>
            GS,
            /// <summary>
            /// South Sudan (Republic of South Sudan)
            /// </summary>
            SS,
            /// <summary>
            /// Spain (Kingdom of Spain)
            /// </summary>
            ES,
            /// <summary>
            /// Sri Lanka (Democratic Socialist Republic of Sri Lanka)
            /// </summary>
            LK,
            /// <summary>
            /// Sudan (Republic of the Sudan)
            /// </summary>
            SD,
            /// <summary>
            /// Suriname (Republic of Suriname)
            /// </summary>
            SR,
            /// <summary>
            /// Svalbard and Jan Mayen
            /// </summary>
            SJ,
            /// <summary>
            /// Sweden (Kingdom of Sweden)
            /// </summary>
            SE,
            /// <summary>
            /// Switzerland (Swiss Confederation)
            /// </summary>
            CH,
            /// <summary>
            /// Syrian Arab Republic
            /// </summary>
            SY,
            /// <summary>
            /// Taiwan, Province of China (Taiwan, Province of China)
            /// </summary>
            TW,
            /// <summary>
            /// Tajikistan (Republic of Tajikistan)
            /// </summary>
            TJ,
            /// <summary>
            /// Tanzania, United Republic of (United Republic of Tanzania)
            /// </summary>
            TZ,
            /// <summary>
            /// Thailand (Kingdom of Thailand)
            /// </summary>
            TH,
            /// <summary>
            /// Timor-Leste (Democratic Republic of Timor-Leste)
            /// </summary>
            TL,
            /// <summary>
            /// Togo (Togolese Republic)
            /// </summary>
            TG,
            /// <summary>
            /// Tokelau
            /// </summary>
            TK,
            /// <summary>
            /// Tonga (Kingdom of Tonga)
            /// </summary>
            TO,
            /// <summary>
            /// Trinidad and Tobago (Republic of Trinidad and Tobago)
            /// </summary>
            TT,
            /// <summary>
            /// Tunisia (Republic of Tunisia)
            /// </summary>
            TN,
            /// <summary>
            /// Türkiye (Republic of Türkiye)
            /// </summary>
            TR,
            /// <summary>
            /// Turkmenistan
            /// </summary>
            TM,
            /// <summary>
            /// Turks and Caicos Islands
            /// </summary>
            TC,
            /// <summary>
            /// Tuvalu
            /// </summary>
            TV,
            /// <summary>
            /// Uganda (Republic of Uganda)
            /// </summary>
            UG,
            /// <summary>
            /// Ukraine
            /// </summary>
            UA,
            /// <summary>
            /// United Arab Emirates
            /// </summary>
            AE,
            /// <summary>
            /// United Kingdom (United Kingdom of Great Britain and Northern Ireland)
            /// </summary>
            GB,
            /// <summary>
            /// United States (United States of America)
            /// </summary>
            US,
            /// <summary>
            /// United States Minor Outlying Islands
            /// </summary>
            UM,
            /// <summary>
            /// Uruguay (Eastern Republic of Uruguay)
            /// </summary>
            UY,
            /// <summary>
            /// Uzbekistan (Republic of Uzbekistan)
            /// </summary>
            UZ,
            /// <summary>
            /// Vanuatu (Republic of Vanuatu)
            /// </summary>
            VU,
            /// <summary>
            /// Venezuela, Bolivarian Republic of (Bolivarian Republic of Venezuela)
            /// </summary>
            VE,
            /// <summary>
            /// Viet Nam (Socialist Republic of Viet Nam)
            /// </summary>
            VN,
            /// <summary>
            /// Virgin Islands, British (British Virgin Islands)
            /// </summary>
            VG,
            /// <summary>
            /// Virgin Islands, U.S. (Virgin Islands of the United States)
            /// </summary>
            VI,
            /// <summary>
            /// Wallis and Futuna
            /// </summary>
            WF,
            /// <summary>
            /// Western Sahara
            /// </summary>
            EH,
            /// <summary>
            /// Yemen (Republic of Yemen)
            /// </summary>
            YE,
            /// <summary>
            /// Zambia (Republic of Zambia)
            /// </summary>
            ZM,
            /// <summary>
            /// Zimbabwe (Republic of Zimbabwe)
            /// </summary>
            ZW,
        }
        /// <summary>
        /// Represents the ISO 3166-1 Alpha-3 three-letter country codes (e.g., "USA", "DEU").
        /// </summary>
        public enum ThreeLetterCode
        {
            /// <summary>
            /// Afghanistan (Islamic Republic of Afghanistan)
            /// </summary>
            AFG,
            /// <summary>
            /// Åland Islands
            /// </summary>
            ALA,
            /// <summary>
            /// Albania (Republic of Albania)
            /// </summary>
            ALB,
            /// <summary>
            /// Algeria (People's Democratic Republic of Algeria)
            /// </summary>
            DZA,
            /// <summary>
            /// American Samoa
            /// </summary>
            ASM,
            /// <summary>
            /// Andorra (Principality of Andorra)
            /// </summary>
            AND,
            /// <summary>
            /// Angola (Republic of Angola)
            /// </summary>
            AGO,
            /// <summary>
            /// Anguilla
            /// </summary>
            AIA,
            /// <summary>
            /// Antarctica
            /// </summary>
            ATA,
            /// <summary>
            /// Antigua and Barbuda
            /// </summary>
            ATG,
            /// <summary>
            /// Argentina (Argentine Republic)
            /// </summary>
            ARG,
            /// <summary>
            /// Armenia (Republic of Armenia)
            /// </summary>
            ARM,
            /// <summary>
            /// Aruba
            /// </summary>
            ABW,
            /// <summary>
            /// Australia
            /// </summary>
            AUS,
            /// <summary>
            /// Austria (Republic of Austria)
            /// </summary>
            AUT,
            /// <summary>
            /// Azerbaijan (Republic of Azerbaijan)
            /// </summary>
            AZE,
            /// <summary>
            /// Bahamas (Commonwealth of the Bahamas)
            /// </summary>
            BHS,
            /// <summary>
            /// Bahrain (Kingdom of Bahrain)
            /// </summary>
            BHR,
            /// <summary>
            /// Bangladesh (People's Republic of Bangladesh)
            /// </summary>
            BGD,
            /// <summary>
            /// Barbados
            /// </summary>
            BRB,
            /// <summary>
            /// Belarus (Republic of Belarus)
            /// </summary>
            BLR,
            /// <summary>
            /// Belgium (Kingdom of Belgium)
            /// </summary>
            BEL,
            /// <summary>
            /// Belize
            /// </summary>
            BLZ,
            /// <summary>
            /// Benin (Republic of Benin)
            /// </summary>
            BEN,
            /// <summary>
            /// Bermuda
            /// </summary>
            BMU,
            /// <summary>
            /// Bhutan (Kingdom of Bhutan)
            /// </summary>
            BTN,
            /// <summary>
            /// Bolivia, Plurinational State of (Plurinational State of Bolivia)
            /// </summary>
            BOL,
            /// <summary>
            /// Bonaire, Sint Eustatius and Saba (Bonaire, Sint Eustatius and Saba)
            /// </summary>
            BES,
            /// <summary>
            /// Bosnia and Herzegovina (Republic of Bosnia and Herzegovina)
            /// </summary>
            BIH,
            /// <summary>
            /// Botswana (Republic of Botswana)
            /// </summary>
            BWA,
            /// <summary>
            /// Bouvet Island
            /// </summary>
            BVT,
            /// <summary>
            /// Brazil (Federative Republic of Brazil)
            /// </summary>
            BRA,
            /// <summary>
            /// British Indian Ocean Territory
            /// </summary>
            IOT,
            /// <summary>
            /// Brunei Darussalam
            /// </summary>
            BRN,
            /// <summary>
            /// Bulgaria (Republic of Bulgaria)
            /// </summary>
            BGR,
            /// <summary>
            /// Burkina Faso
            /// </summary>
            BFA,
            /// <summary>
            /// Burundi (Republic of Burundi)
            /// </summary>
            BDI,
            /// <summary>
            /// Cabo Verde (Republic of Cabo Verde)
            /// </summary>
            CPV,
            /// <summary>
            /// Cambodia (Kingdom of Cambodia)
            /// </summary>
            KHM,
            /// <summary>
            /// Cameroon (Republic of Cameroon)
            /// </summary>
            CMR,
            /// <summary>
            /// Canada
            /// </summary>
            CAN,
            /// <summary>
            /// Cayman Islands
            /// </summary>
            CYM,
            /// <summary>
            /// Central African Republic
            /// </summary>
            CAF,
            /// <summary>
            /// Chad (Republic of Chad)
            /// </summary>
            TCD,
            /// <summary>
            /// Chile (Republic of Chile)
            /// </summary>
            CHL,
            /// <summary>
            /// China (People's Republic of China)
            /// </summary>
            CHN,
            /// <summary>
            /// Christmas Island
            /// </summary>
            CXR,
            /// <summary>
            /// Cocos (Keeling) Islands
            /// </summary>
            CCK,
            /// <summary>
            /// Colombia (Republic of Colombia)
            /// </summary>
            COL,
            /// <summary>
            /// Comoros (Union of the Comoros)
            /// </summary>
            COM,
            /// <summary>
            /// Congo (Republic of the Congo)
            /// </summary>
            COG,
            /// <summary>
            /// Congo, The Democratic Republic of the
            /// </summary>
            COD,
            /// <summary>
            /// Cook Islands
            /// </summary>
            COK,
            /// <summary>
            /// Costa Rica (Republic of Costa Rica)
            /// </summary>
            CRI,
            /// <summary>
            /// Côte d'Ivoire (Republic of Côte d'Ivoire)
            /// </summary>
            CIV,
            /// <summary>
            /// Croatia (Republic of Croatia)
            /// </summary>
            HRV,
            /// <summary>
            /// Cuba (Republic of Cuba)
            /// </summary>
            CUB,
            /// <summary>
            /// Curaçao (Curaçao)
            /// </summary>
            CUW,
            /// <summary>
            /// Cyprus (Republic of Cyprus)
            /// </summary>
            CYP,
            /// <summary>
            /// Czechia (Czech Republic)
            /// </summary>
            CZE,
            /// <summary>
            /// Denmark (Kingdom of Denmark)
            /// </summary>
            DNK,
            /// <summary>
            /// Djibouti (Republic of Djibouti)
            /// </summary>
            DJI,
            /// <summary>
            /// Dominica (Commonwealth of Dominica)
            /// </summary>
            DMA,
            /// <summary>
            /// Dominican Republic
            /// </summary>
            DOM,
            /// <summary>
            /// Ecuador (Republic of Ecuador)
            /// </summary>
            ECU,
            /// <summary>
            /// Egypt (Arab Republic of Egypt)
            /// </summary>
            EGY,
            /// <summary>
            /// El Salvador (Republic of El Salvador)
            /// </summary>
            SLV,
            /// <summary>
            /// Equatorial Guinea (Republic of Equatorial Guinea)
            /// </summary>
            GNQ,
            /// <summary>
            /// Eritrea (the State of Eritrea)
            /// </summary>
            ERI,
            /// <summary>
            /// Estonia (Republic of Estonia)
            /// </summary>
            EST,
            /// <summary>
            /// Eswatini (Kingdom of Eswatini)
            /// </summary>
            SWZ,
            /// <summary>
            /// Ethiopia (Federal Democratic Republic of Ethiopia)
            /// </summary>
            ETH,
            /// <summary>
            /// Falkland Islands (Malvinas)
            /// </summary>
            FLK,
            /// <summary>
            /// Faroe Islands
            /// </summary>
            FRO,
            /// <summary>
            /// Fiji (Republic of Fiji)
            /// </summary>
            FJI,
            /// <summary>
            /// Finland (Republic of Finland)
            /// </summary>
            FIN,
            /// <summary>
            /// France (French Republic)
            /// </summary>
            FRA,
            /// <summary>
            /// French Guiana
            /// </summary>
            GUF,
            /// <summary>
            /// French Polynesia
            /// </summary>
            PYF,
            /// <summary>
            /// French Southern Territories
            /// </summary>
            ATF,
            /// <summary>
            /// Gabon (Gabonese Republic)
            /// </summary>
            GAB,
            /// <summary>
            /// Gambia (Republic of the Gambia)
            /// </summary>
            GMB,
            /// <summary>
            /// Georgia
            /// </summary>
            GEO,
            /// <summary>
            /// Germany (Federal Republic of Germany)
            /// </summary>
            DEU,
            /// <summary>
            /// Ghana (Republic of Ghana)
            /// </summary>
            GHA,
            /// <summary>
            /// Gibraltar
            /// </summary>
            GIB,
            /// <summary>
            /// Greece (Hellenic Republic)
            /// </summary>
            GRC,
            /// <summary>
            /// Greenland
            /// </summary>
            GRL,
            /// <summary>
            /// Grenada
            /// </summary>
            GRD,
            /// <summary>
            /// Guadeloupe
            /// </summary>
            GLP,
            /// <summary>
            /// Guam
            /// </summary>
            GUM,
            /// <summary>
            /// Guatemala (Republic of Guatemala)
            /// </summary>
            GTM,
            /// <summary>
            /// Guernsey
            /// </summary>
            GGY,
            /// <summary>
            /// Guinea (Republic of Guinea)
            /// </summary>
            GIN,
            /// <summary>
            /// Guinea-Bissau (Republic of Guinea-Bissau)
            /// </summary>
            GNB,
            /// <summary>
            /// Guyana (Republic of Guyana)
            /// </summary>
            GUY,
            /// <summary>
            /// Haiti (Republic of Haiti)
            /// </summary>
            HTI,
            /// <summary>
            /// Heard Island and McDonald Islands
            /// </summary>
            HMD,
            /// <summary>
            /// Holy See (Vatican City State)
            /// </summary>
            VAT,
            /// <summary>
            /// Honduras (Republic of Honduras)
            /// </summary>
            HND,
            /// <summary>
            /// Hong Kong (Hong Kong Special Administrative Region of China)
            /// </summary>
            HKG,
            /// <summary>
            /// Hungary (Hungary)
            /// </summary>
            HUN,
            /// <summary>
            /// Iceland (Republic of Iceland)
            /// </summary>
            ISL,
            /// <summary>
            /// India (Republic of India)
            /// </summary>
            IND,
            /// <summary>
            /// Indonesia (Republic of Indonesia)
            /// </summary>
            IDN,
            /// <summary>
            /// Iran, Islamic Republic of (Islamic Republic of Iran)
            /// </summary>
            IRN,
            /// <summary>
            /// Iraq (Republic of Iraq)
            /// </summary>
            IRQ,
            /// <summary>
            /// Ireland
            /// </summary>
            IRL,
            /// <summary>
            /// Isle of Man
            /// </summary>
            IMN,
            /// <summary>
            /// Israel (State of Israel)
            /// </summary>
            ISR,
            /// <summary>
            /// Italy (Italian Republic)
            /// </summary>
            ITA,
            /// <summary>
            /// Jamaica
            /// </summary>
            JAM,
            /// <summary>
            /// Japan
            /// </summary>
            JPN,
            /// <summary>
            /// Jersey
            /// </summary>
            JEY,
            /// <summary>
            /// Jordan (Hashemite Kingdom of Jordan)
            /// </summary>
            JOR,
            /// <summary>
            /// Kazakhstan (Republic of Kazakhstan)
            /// </summary>
            KAZ,
            /// <summary>
            /// Kenya (Republic of Kenya)
            /// </summary>
            KEN,
            /// <summary>
            /// Kiribati (Republic of Kiribati)
            /// </summary>
            KIR,
            /// <summary>
            /// Korea, Democratic People's Republic of (Democratic People's Republic of Korea)
            /// </summary>
            PRK,
            /// <summary>
            /// Korea, Republic of
            /// </summary>
            KOR,
            /// <summary>
            /// Kuwait (State of Kuwait)
            /// </summary>
            KWT,
            /// <summary>
            /// Kyrgyzstan (Kyrgyz Republic)
            /// </summary>
            KGZ,
            /// <summary>
            /// Lao People's Democratic Republic
            /// </summary>
            LAO,
            /// <summary>
            /// Latvia (Republic of Latvia)
            /// </summary>
            LVA,
            /// <summary>
            /// Lebanon (Lebanese Republic)
            /// </summary>
            LBN,
            /// <summary>
            /// Lesotho (Kingdom of Lesotho)
            /// </summary>
            LSO,
            /// <summary>
            /// Liberia (Republic of Liberia)
            /// </summary>
            LBR,
            /// <summary>
            /// Libya (Libya)
            /// </summary>
            LBY,
            /// <summary>
            /// Liechtenstein (Principality of Liechtenstein)
            /// </summary>
            LIE,
            /// <summary>
            /// Lithuania (Republic of Lithuania)
            /// </summary>
            LTU,
            /// <summary>
            /// Luxembourg (Grand Duchy of Luxembourg)
            /// </summary>
            LUX,
            /// <summary>
            /// Macao (Macao Special Administrative Region of China)
            /// </summary>
            MAC,
            /// <summary>
            /// Madagascar (Republic of Madagascar)
            /// </summary>
            MDG,
            /// <summary>
            /// Malawi (Republic of Malawi)
            /// </summary>
            MWI,
            /// <summary>
            /// Malaysia
            /// </summary>
            MYS,
            /// <summary>
            /// Maldives (Republic of Maldives)
            /// </summary>
            MDV,
            /// <summary>
            /// Mali (Republic of Mali)
            /// </summary>
            MLI,
            /// <summary>
            /// Malta (Republic of Malta)
            /// </summary>
            MLT,
            /// <summary>
            /// Marshall Islands (Republic of the Marshall Islands)
            /// </summary>
            MHL,
            /// <summary>
            /// Martinique
            /// </summary>
            MTQ,
            /// <summary>
            /// Mauritania (Islamic Republic of Mauritania)
            /// </summary>
            MRT,
            /// <summary>
            /// Mauritius (Republic of Mauritius)
            /// </summary>
            MUS,
            /// <summary>
            /// Mayotte
            /// </summary>
            MYT,
            /// <summary>
            /// Mexico (United Mexican States)
            /// </summary>
            MEX,
            /// <summary>
            /// Micronesia, Federated States of (Federated States of Micronesia)
            /// </summary>
            FSM,
            /// <summary>
            /// Moldova, Republic of (Republic of Moldova)
            /// </summary>
            MDA,
            /// <summary>
            /// Monaco (Principality of Monaco)
            /// </summary>
            MCO,
            /// <summary>
            /// Mongolia
            /// </summary>
            MNG,
            /// <summary>
            /// Montenegro (Montenegro)
            /// </summary>
            MNE,
            /// <summary>
            /// Montserrat
            /// </summary>
            MSR,
            /// <summary>
            /// Morocco (Kingdom of Morocco)
            /// </summary>
            MAR,
            /// <summary>
            /// Mozambique (Republic of Mozambique)
            /// </summary>
            MOZ,
            /// <summary>
            /// Myanmar (Republic of Myanmar)
            /// </summary>
            MMR,
            /// <summary>
            /// Namibia (Republic of Namibia)
            /// </summary>
            NAM,
            /// <summary>
            /// Nauru (Republic of Nauru)
            /// </summary>
            NRU,
            /// <summary>
            /// Nepal (Federal Democratic Republic of Nepal)
            /// </summary>
            NPL,
            /// <summary>
            /// Netherlands (Kingdom of the Netherlands)
            /// </summary>
            NLD,
            /// <summary>
            /// New Caledonia
            /// </summary>
            NCL,
            /// <summary>
            /// New Zealand
            /// </summary>
            NZL,
            /// <summary>
            /// Nicaragua (Republic of Nicaragua)
            /// </summary>
            NIC,
            /// <summary>
            /// Niger (Republic of the Niger)
            /// </summary>
            NER,
            /// <summary>
            /// Nigeria (Federal Republic of Nigeria)
            /// </summary>
            NGA,
            /// <summary>
            /// Niue (Niue)
            /// </summary>
            NIU,
            /// <summary>
            /// Norfolk Island
            /// </summary>
            NFK,
            /// <summary>
            /// North Macedonia (Republic of North Macedonia)
            /// </summary>
            MKD,
            /// <summary>
            /// Northern Mariana Islands (Commonwealth of the Northern Mariana Islands)
            /// </summary>
            MNP,
            /// <summary>
            /// Norway (Kingdom of Norway)
            /// </summary>
            NOR,
            /// <summary>
            /// Oman (Sultanate of Oman)
            /// </summary>
            OMN,
            /// <summary>
            /// Pakistan (Islamic Republic of Pakistan)
            /// </summary>
            PAK,
            /// <summary>
            /// Palau (Republic of Palau)
            /// </summary>
            PLW,
            /// <summary>
            /// Palestine, State of (the State of Palestine)
            /// </summary>
            PSE,
            /// <summary>
            /// Panama (Republic of Panama)
            /// </summary>
            PAN,
            /// <summary>
            /// Papua New Guinea (Independent State of Papua New Guinea)
            /// </summary>
            PNG,
            /// <summary>
            /// Paraguay (Republic of Paraguay)
            /// </summary>
            PRY,
            /// <summary>
            /// Peru (Republic of Peru)
            /// </summary>
            PER,
            /// <summary>
            /// Philippines (Republic of the Philippines)
            /// </summary>
            PHL,
            /// <summary>
            /// Pitcairn
            /// </summary>
            PCN,
            /// <summary>
            /// Poland (Republic of Poland)
            /// </summary>
            POL,
            /// <summary>
            /// Portugal (Portuguese Republic)
            /// </summary>
            PRT,
            /// <summary>
            /// Puerto Rico
            /// </summary>
            PRI,
            /// <summary>
            /// Qatar (State of Qatar)
            /// </summary>
            QAT,
            /// <summary>
            /// Réunion
            /// </summary>
            REU,
            /// <summary>
            /// Romania
            /// </summary>
            ROU,
            /// <summary>
            /// Russian Federation
            /// </summary>
            RUS,
            /// <summary>
            /// Rwanda (Rwandese Republic)
            /// </summary>
            RWA,
            /// <summary>
            /// Saint Barthélemy
            /// </summary>
            BLM,
            /// <summary>
            /// Saint Helena, Ascension and Tristan da Cunha
            /// </summary>
            SHN,
            /// <summary>
            /// Saint Kitts and Nevis
            /// </summary>
            KNA,
            /// <summary>
            /// Saint Lucia
            /// </summary>
            LCA,
            /// <summary>
            /// Saint Martin (French part)
            /// </summary>
            MAF,
            /// <summary>
            /// Saint Pierre and Miquelon
            /// </summary>
            SPM,
            /// <summary>
            /// Saint Vincent and the Grenadines
            /// </summary>
            VCT,
            /// <summary>
            /// Samoa (Independent State of Samoa)
            /// </summary>
            WSM,
            /// <summary>
            /// San Marino (Republic of San Marino)
            /// </summary>
            SMR,
            /// <summary>
            /// Sao Tome and Principe (Democratic Republic of Sao Tome and Principe)
            /// </summary>
            STP,
            /// <summary>
            /// Saudi Arabia (Kingdom of Saudi Arabia)
            /// </summary>
            SAU,
            /// <summary>
            /// Senegal (Republic of Senegal)
            /// </summary>
            SEN,
            /// <summary>
            /// Serbia (Republic of Serbia)
            /// </summary>
            SRB,
            /// <summary>
            /// Seychelles (Republic of Seychelles)
            /// </summary>
            SYC,
            /// <summary>
            /// Sierra Leone (Republic of Sierra Leone)
            /// </summary>
            SLE,
            /// <summary>
            /// Singapore (Republic of Singapore)
            /// </summary>
            SGP,
            /// <summary>
            /// Sint Maarten (Dutch part) (Sint Maarten (Dutch part))
            /// </summary>
            SXM,
            /// <summary>
            /// Slovakia (Slovak Republic)
            /// </summary>
            SVK,
            /// <summary>
            /// Slovenia (Republic of Slovenia)
            /// </summary>
            SVN,
            /// <summary>
            /// Solomon Islands
            /// </summary>
            SLB,
            /// <summary>
            /// Somalia (Federal Republic of Somalia)
            /// </summary>
            SOM,
            /// <summary>
            /// South Africa (Republic of South Africa)
            /// </summary>
            ZAF,
            /// <summary>
            /// South Georgia and the South Sandwich Islands
            /// </summary>
            SGS,
            /// <summary>
            /// South Sudan (Republic of South Sudan)
            /// </summary>
            SSD,
            /// <summary>
            /// Spain (Kingdom of Spain)
            /// </summary>
            ESP,
            /// <summary>
            /// Sri Lanka (Democratic Socialist Republic of Sri Lanka)
            /// </summary>
            LKA,
            /// <summary>
            /// Sudan (Republic of the Sudan)
            /// </summary>
            SDN,
            /// <summary>
            /// Suriname (Republic of Suriname)
            /// </summary>
            SUR,
            /// <summary>
            /// Svalbard and Jan Mayen
            /// </summary>
            SJM,
            /// <summary>
            /// Sweden (Kingdom of Sweden)
            /// </summary>
            SWE,
            /// <summary>
            /// Switzerland (Swiss Confederation)
            /// </summary>
            CHE,
            /// <summary>
            /// Syrian Arab Republic
            /// </summary>
            SYR,
            /// <summary>
            /// Taiwan, Province of China (Taiwan, Province of China)
            /// </summary>
            TWN,
            /// <summary>
            /// Tajikistan (Republic of Tajikistan)
            /// </summary>
            TJK,
            /// <summary>
            /// Tanzania, United Republic of (United Republic of Tanzania)
            /// </summary>
            TZA,
            /// <summary>
            /// Thailand (Kingdom of Thailand)
            /// </summary>
            THA,
            /// <summary>
            /// Timor-Leste (Democratic Republic of Timor-Leste)
            /// </summary>
            TLS,
            /// <summary>
            /// Togo (Togolese Republic)
            /// </summary>
            TGO,
            /// <summary>
            /// Tokelau
            /// </summary>
            TKL,
            /// <summary>
            /// Tonga (Kingdom of Tonga)
            /// </summary>
            TON,
            /// <summary>
            /// Trinidad and Tobago (Republic of Trinidad and Tobago)
            /// </summary>
            TTO,
            /// <summary>
            /// Tunisia (Republic of Tunisia)
            /// </summary>
            TUN,
            /// <summary>
            /// Türkiye (Republic of Türkiye)
            /// </summary>
            TUR,
            /// <summary>
            /// Turkmenistan
            /// </summary>
            TKM,
            /// <summary>
            /// Turks and Caicos Islands
            /// </summary>
            TCA,
            /// <summary>
            /// Tuvalu
            /// </summary>
            TUV,
            /// <summary>
            /// Uganda (Republic of Uganda)
            /// </summary>
            UGA,
            /// <summary>
            /// Ukraine
            /// </summary>
            UKR,
            /// <summary>
            /// United Arab Emirates
            /// </summary>
            ARE,
            /// <summary>
            /// United Kingdom (United Kingdom of Great Britain and Northern Ireland)
            /// </summary>
            GBR,
            /// <summary>
            /// United States (United States of America)
            /// </summary>
            USA,
            /// <summary>
            /// United States Minor Outlying Islands
            /// </summary>
            UMI,
            /// <summary>
            /// Uruguay (Eastern Republic of Uruguay)
            /// </summary>
            URY,
            /// <summary>
            /// Uzbekistan (Republic of Uzbekistan)
            /// </summary>
            UZB,
            /// <summary>
            /// Vanuatu (Republic of Vanuatu)
            /// </summary>
            VUT,
            /// <summary>
            /// Venezuela, Bolivarian Republic of (Bolivarian Republic of Venezuela)
            /// </summary>
            VEN,
            /// <summary>
            /// Viet Nam (Socialist Republic of Viet Nam)
            /// </summary>
            VNM,
            /// <summary>
            /// Virgin Islands, British (British Virgin Islands)
            /// </summary>
            VGB,
            /// <summary>
            /// Virgin Islands, U.S. (Virgin Islands of the United States)
            /// </summary>
            VIR,
            /// <summary>
            /// Wallis and Futuna
            /// </summary>
            WLF,
            /// <summary>
            /// Western Sahara
            /// </summary>
            ESH,
            /// <summary>
            /// Yemen (Republic of Yemen)
            /// </summary>
            YEM,
            /// <summary>
            /// Zambia (Republic of Zambia)
            /// </summary>
            ZMB,
            /// <summary>
            /// Zimbabwe (Republic of Zimbabwe)
            /// </summary>
            ZWE,
        }
    }
}
