using System.Reflection;
using System.Text;
using Country.Reference.Iso3166.Generators.Handlers;
using Country.Reference.Iso3166.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
namespace Country.Reference.Iso3166.Generators;

[Generator]
public class CountryCodeEnumsGenerator : BaseIncrementalGenerator
{
    protected override string HintName => "CountryCode.g.cs";

    private const string StubSource = """
                                      // <auto-generated>
                                      //     This file was generated by Country.Reference.Iso3166.Generators source generator.
                                      //     Do not modify this file manually.
                                      // </auto-generated>
                                      #nullable enable
                                      using System.Collections.Generic;
                                      namespace Country.Reference.Iso3166
                                      {
                                          /// <summary> 
                                          /// Country codes ISO3166 (M49) 
                                          /// </summary>
                                          public static class CountryCode
                                          {
                                              /// <summary>
                                              /// Represents the ISO 3166-1 Alpha-2 two-letter country codes (e.g., "US", "DE").
                                              /// </summary>
                                              public enum TwoLetterCode
                                              {
                                                  /// <summary> 
                                                  /// Unknown country code 
                                                  /// </summary>
                                                  Undefined,
                                              }
                                              /// <summary>
                                              /// Represents the ISO 3166-1 Alpha-3 three-letter country codes (e.g., "USA", "DEU").
                                              /// </summary>
                                              public enum ThreeLetterCode
                                              {
                                                  /// <summary> 
                                                  /// Unknown country code 
                                                  /// </summary>
                                                  Undefined,
                                              }
                                          }
                                      }
                                      """;

    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ErrorFactory.Clear();

        var csvContentProvider = context.CompilationProvider.Select(ReadCsvResource);

        context.RegisterSourceOutput(csvContentProvider, (spc, content) => GenerateSourceOutput(content, spc));
    }

    static string ReadCsvResource(Compilation compilation, CancellationToken ct)
    {
        try
        {
            return LoadCsvResources(Assembly.GetExecutingAssembly());
        }
        catch (Exception ex)
        {
            var errorMsg = $"{Constants.ErrorMark}:{ex.Message}";
            return errorMsg;
        }
    }

    private new void GenerateSourceOutput(string originalCsv, SourceProductionContext spc)
    {
        try
        {
            if (HasResourceErrors(originalCsv, out var errorMessages))
            {
                foreach (var msg in errorMessages)
                    ReportResourceError(msg);

                AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Database);
                return;
            }

            var loader = new CsvCountryLoader(originalCsv);
            var sb = CreateSourceBuilder(
                Constants.GeneratorName,
                Constants.DefaultNamespace,
                [
                    "System.Collections.Generic"
                ]);

            sb.AppendLine("    /// <summary>")
                .AppendLine("    /// Country codes ISO3166 (M49)")
                .AppendLine("    /// </summary>")
                .AppendLine("    public static class CountryCode")
                .AppendLine("    {");

            GenerateCountryEnumSection(sb, "TwoLetterCode", loader.ActualCountries, "Represents the ISO 3166-1 Alpha-2 two-letter country codes (e.g., \"US\", \"DE\").", false);
            GenerateCountryEnumSection(sb, "ThreeLetterCode", loader.ActualCountries, "Represents the ISO 3166-1 Alpha-3 three-letter country codes (e.g., \"USA\", \"DEU\").", true);

            sb.AppendLine("    }")
                .AppendLine("}");
            spc.AddSource(HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
        catch (Exception ex)
        {
            ErrorFactory.Create(new ErrorDescription
            {
                DiagnosticDescriptor = new DiagnosticDescriptor(
                    DiagnosticDescriptors.UnexpectedErrorId,
                    Constants.DiagnosticsTitle,
                    $"Unexpected exception: {ex.Message}",
                    string.Empty,
                    DiagnosticSeverity.Error,
                    true),
                GeneratorType = GeneratorType.Database
            });
            AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Database);
        }
    }

    private static bool HasResourceErrors(string originalCsv, out List<string> messages)
    {
        messages = [];
        if (originalCsv.StartsWith(Constants.ErrorMark)) messages.Add("original:" + originalCsv);
        return messages.Count > 0;
    }

    private static void GenerateCountryEnumSection(
        StringBuilder sb,
        string propertyName,
        List<Models.Country> countryList,
        string summary,
        bool isThreeLetterCode)
    {
        sb.AppendLine(
                "        /// <summary>")
            .AppendLine(
                $"        /// {summary}")
            .AppendLine(
                "        /// </summary>");
        sb.AppendLine(
                $"        public enum {propertyName}")
            .AppendLine("        {");
        foreach (var c in countryList)
        {
            sb.AppendLine(
                    "            /// <summary>")
                .AppendLine(
                    $"            /// {c.Name}")
                .AppendLine(
                    "            /// </summary>");
            sb.AppendLine(
                !isThreeLetterCode ? $"            {c.CodeAlpha2}," : $"            {c.CodeAlpha3},");
        }

        sb.AppendLine("        }");
    }

    private void ReportResourceError(string msg)
    {
        var parts = msg.Split([':'], 2);
        var name = parts[0];
        var text = parts.Length > 1 ? parts[1] : "Unknown error";

        ErrorFactory.Create(new ErrorDescription
        {
            DiagnosticDescriptor = new DiagnosticDescriptor(
                DiagnosticDescriptors.ResourceLoadErrorId,
                Constants.DiagnosticsTitle,
                $"Failed to load {name} resource: {text}",
                string.Empty,
                DiagnosticSeverity.Error,
                true),
            GeneratorType = GeneratorType.Database
        });
    }
}