using System.Reflection;
using System.Text;
using Country.Reference.Iso3166.Generators.Handlers;
using Country.Reference.Iso3166.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
namespace Country.Reference.Iso3166.Generators;

[Generator]
public class LocalCountryDatabaseGenerator : BaseIncrementalGenerator
{
    protected override string HintName => "LocalCountryDatabase.g.cs";

    private const string StubSource = """
                                      // <auto-generated>
                                      //     This file was generated by Country.Reference.Iso3166.Generators source generator.
                                      //     Do not modify this file manually.
                                      // </auto-generated>
                                      #nullable enable
                                      using System.Collections.Generic;
                                      using Country.Reference.Iso3166.Models;
                                      namespace Country.Reference.Iso3166
                                      {
                                          /// <summary> 
                                          /// Country information ISO3166 (M49) 
                                          /// </summary>
                                          internal static class LocalCountryDatabase
                                          {
                                              public static IReadOnlyList<Models.Country> ActualCountries = new List<Models.Country>();
                                          }
                                      }
                                      """;

    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ErrorFactory.Clear();

        var csvContentProvider = context.CompilationProvider.Select(ReadCsvResource);

        context.RegisterSourceOutput(csvContentProvider, (spc, content) => GenerateSourceOutput(content, spc));
    }

    static string ReadCsvResource(Compilation compilation, CancellationToken ct)
    {
        try
        {
            return LoadCsvResources(Assembly.GetExecutingAssembly());
        }
        catch (Exception ex)
        {
            var errorMsg = $"{Constants.ErrorMark}:{ex.Message}";
            return errorMsg;
        }
    }

    private new void GenerateSourceOutput(string originalCsv, SourceProductionContext spc)
    {
        try
        {
            if (HasResourceErrors(originalCsv, out var errorMessages))
            {
                foreach (var msg in errorMessages)
                    ReportResourceError(msg);

                AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Database);
                return;
            }

            var loader = new CsvCountryLoader(originalCsv);
            var sb = CreateSourceBuilder(
                Constants.GeneratorName,
                Constants.DefaultNamespace,
                [
                    "System.Collections.Generic",
                    "Country.Reference.Iso3166.Models"
                ]);

            sb.AppendLine("    /// <summary>")
                .AppendLine("    /// Country information ISO3166 (M49)")
                .AppendLine("    /// </summary>")
                .AppendLine("    internal static class LocalCountryDatabase")
                .AppendLine("    {");

            GenerateCountrySection(sb, "ActualCountries", loader.ActualCountries);

            sb.AppendLine("    }")
                .AppendLine("}");
            spc.AddSource(HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
        catch (Exception ex)
        {
            ErrorFactory.Create(new ErrorDescription
            {
                DiagnosticDescriptor = new DiagnosticDescriptor(
                    DiagnosticDescriptors.UnexpectedErrorId,
                    Constants.DiagnosticsTitle,
                    $"Unexpected exception: {ex.Message}",
                    string.Empty,
                    DiagnosticSeverity.Error,
                    true),
                GeneratorType = GeneratorType.Database
            });
            AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Database);
        }
    }

    private static bool HasResourceErrors(string originalCsv, out List<string> messages)
    {
        messages = [];
        if (originalCsv.StartsWith(Constants.ErrorMark)) messages.Add("original:" + originalCsv);
        return messages.Count > 0;
    }

    private static void GenerateCountrySection(StringBuilder sb, string propertyName, List<Models.Country> countryList)
    {
        sb.AppendLine(
                $"        public static IReadOnlyList<Models.Country> {propertyName} = new List<Models.Country>()")
            .AppendLine("        {");
        foreach (var c in countryList)
        {
            sb.AppendLine(
                $"            new(\"{c.Name}\", CountryCode.TwoLetterCode.{c.CodeAlpha2}, CountryCode.ThreeLetterCode.{c.CodeAlpha3}, \"{c.NumericCode}\"),");
        }

        sb.AppendLine("        };");
    }

    private void ReportResourceError(string msg)
    {
        var parts = msg.Split([':'], 2);
        var name = parts[0];
        var text = parts.Length > 1 ? parts[1] : "Unknown error";

        ErrorFactory.Create(new ErrorDescription
        {
            DiagnosticDescriptor = new DiagnosticDescriptor(
                DiagnosticDescriptors.ResourceLoadErrorId,
                Constants.DiagnosticsTitle,
                $"Failed to load {name} resource: {text}",
                string.Empty,
                DiagnosticSeverity.Error,
                true),
            GeneratorType = GeneratorType.Database
        });
    }
}