using HawkN.Iso.Countries.Generators.Tests.Helpers;
using Microsoft.CodeAnalysis;
namespace HawkN.Iso.Countries.Generators.Tests;

public class CountryCodeEnumsGeneratorTests
{
    [Fact]
    public void Generator_Should_Produce_Source_With_Enums()
    {
        // Arrange
        // Пустой исходный код, так как генератор работает на основе ресурсов, а не синтаксиса
        string inputSource = "namespace Test { }";

        // Act
        var (diagnostics, output) = GeneratorTestHelper.GetGeneratedOutput<CountryCodeEnumsGenerator>(inputSource);

        // Assert
        Assert.Empty(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));
        Assert.Contains("public enum TwoLetterCode", output);
        Assert.Contains("public enum ThreeLetterCode", output);
        Assert.Contains("namespace HawkN.Iso.Countries", output);
        Assert.Contains("AF,", output);
        Assert.Contains("AFG,", output);
    }

    [Fact]
    public void Generator_Should_Add_AutoGenerated_Header()
    {
        // Act
        var (_, output) = GeneratorTestHelper.GetGeneratedOutput<CountryCodeEnumsGenerator>("");

        // Assert
        Assert.StartsWith("// <auto-generated>", output);
        Assert.Contains("This file was generated by HawkN.Iso.Countries.Generators", output);
    }

    [Fact]
    public void Generator_Should_Include_DataSource_Information()
    {
        // Act
        var (_, output) = GeneratorTestHelper.GetGeneratedOutput<CountryCodeEnumsGenerator>("");

        // Assert
        Assert.Contains("Source URL: https://unstats.un.org/unsd/methodology/m49/overview", output);
    }
}