// <auto-generated>
//     This file was generated by HawkN.Iso.Countries.Currencies.Generators source generator
//     Release: release-48
//     CLDR URL: https://github.com/unicode-org/cldr
//     Do not modify this file manually.
// </auto-generated>
#nullable enable
using System.Collections.Generic;
using System.Collections.Immutable;
using HawkN.Iso.Countries;
using HawkN.Iso.Currencies;
using HawkN.Iso.Countries.Currencies.Models;
namespace HawkN.Iso.Countries.Currencies
{
   /// <summary>
   /// Provides fast ISO 3166 → ISO 4217 country-to-currency mapping.
   /// Generated from Unicode CLDR supplemental data.
   /// </summary>
   internal static class CountryCurrencyMap
   {
      /// <summary>
      /// Raw string-based data generated from CLDR.
      /// Parsed and validated at type initialization.
      /// </summary>
      internal static ImmutableArray<CountryCurrencyInfoRow> RawData = ImmutableArray.Create(new CountryCurrencyInfoRow[]
         {
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AC",
                    PrimaryCurrency = "SHP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AD",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AE",
                    PrimaryCurrency = "AED",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AF",
                    PrimaryCurrency = "AFN",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AG",
                    PrimaryCurrency = "XCD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AI",
                    PrimaryCurrency = "XCD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AL",
                    PrimaryCurrency = "ALL",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AM",
                    PrimaryCurrency = "AMD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AO",
                    PrimaryCurrency = "AOA",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AQ",
                    PrimaryCurrency = "XXX",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AR",
                    PrimaryCurrency = "ARS",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AS",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AT",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AU",
                    PrimaryCurrency = "AUD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AW",
                    PrimaryCurrency = "AWG",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AX",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "AZ",
                    PrimaryCurrency = "AZN",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BA",
                    PrimaryCurrency = "BAM",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BB",
                    PrimaryCurrency = "BBD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BD",
                    PrimaryCurrency = "BDT",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BE",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BF",
                    PrimaryCurrency = "XOF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BG",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BH",
                    PrimaryCurrency = "BHD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BI",
                    PrimaryCurrency = "BIF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BJ",
                    PrimaryCurrency = "XOF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BL",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BM",
                    PrimaryCurrency = "BMD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BN",
                    PrimaryCurrency = "BND",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BO",
                    PrimaryCurrency = "BOB",
                    SecondaryCurrencies = new []
                    {
                        "BOV",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BQ",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BR",
                    PrimaryCurrency = "BRL",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BS",
                    PrimaryCurrency = "BSD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BT",
                    PrimaryCurrency = "BTN",
                    SecondaryCurrencies = new []
                    {
                        "INR",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BV",
                    PrimaryCurrency = "NOK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BW",
                    PrimaryCurrency = "BWP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BY",
                    PrimaryCurrency = "BYN",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "BZ",
                    PrimaryCurrency = "BZD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CA",
                    PrimaryCurrency = "CAD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CC",
                    PrimaryCurrency = "AUD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CD",
                    PrimaryCurrency = "CDF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CF",
                    PrimaryCurrency = "XAF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CG",
                    PrimaryCurrency = "XAF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CH",
                    PrimaryCurrency = "CHF",
                    SecondaryCurrencies = new []
                    {
                        "CHE",
                        "CHW",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CI",
                    PrimaryCurrency = "XOF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CK",
                    PrimaryCurrency = "NZD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CL",
                    PrimaryCurrency = "CLP",
                    SecondaryCurrencies = new []
                    {
                        "CLF",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CM",
                    PrimaryCurrency = "XAF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CN",
                    PrimaryCurrency = "CNY",
                    SecondaryCurrencies = new []
                    {
                        "CNH",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CO",
                    PrimaryCurrency = "COP",
                    SecondaryCurrencies = new []
                    {
                        "COU",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CP",
                    PrimaryCurrency = "XXX",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CR",
                    PrimaryCurrency = "CRC",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CU",
                    PrimaryCurrency = "CUP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CV",
                    PrimaryCurrency = "CVE",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CW",
                    PrimaryCurrency = "XCG",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CX",
                    PrimaryCurrency = "AUD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CY",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "CZ",
                    PrimaryCurrency = "CZK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "DE",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "DG",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "DJ",
                    PrimaryCurrency = "DJF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "DK",
                    PrimaryCurrency = "DKK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "DM",
                    PrimaryCurrency = "XCD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "DO",
                    PrimaryCurrency = "DOP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "DZ",
                    PrimaryCurrency = "DZD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "EA",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "EC",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "EE",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "EG",
                    PrimaryCurrency = "EGP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "EH",
                    PrimaryCurrency = "MAD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ER",
                    PrimaryCurrency = "ERN",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ES",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ET",
                    PrimaryCurrency = "ETB",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "EU",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "FI",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "FJ",
                    PrimaryCurrency = "FJD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "FK",
                    PrimaryCurrency = "FKP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "FM",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "FO",
                    PrimaryCurrency = "DKK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "FR",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GA",
                    PrimaryCurrency = "XAF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GB",
                    PrimaryCurrency = "GBP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GD",
                    PrimaryCurrency = "XCD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GE",
                    PrimaryCurrency = "GEL",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GF",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GG",
                    PrimaryCurrency = "GBP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GH",
                    PrimaryCurrency = "GHS",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GI",
                    PrimaryCurrency = "GIP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GL",
                    PrimaryCurrency = "DKK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GM",
                    PrimaryCurrency = "GMD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GN",
                    PrimaryCurrency = "GNF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GP",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GQ",
                    PrimaryCurrency = "XAF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GR",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GS",
                    PrimaryCurrency = "GBP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GT",
                    PrimaryCurrency = "GTQ",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GU",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GW",
                    PrimaryCurrency = "XOF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "GY",
                    PrimaryCurrency = "GYD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "HK",
                    PrimaryCurrency = "HKD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "HM",
                    PrimaryCurrency = "AUD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "HN",
                    PrimaryCurrency = "HNL",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "HR",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "HT",
                    PrimaryCurrency = "HTG",
                    SecondaryCurrencies = new []
                    {
                        "USD",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "HU",
                    PrimaryCurrency = "HUF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IC",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ID",
                    PrimaryCurrency = "IDR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IE",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IL",
                    PrimaryCurrency = "ILS",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IM",
                    PrimaryCurrency = "GBP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IN",
                    PrimaryCurrency = "INR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IO",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IQ",
                    PrimaryCurrency = "IQD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IR",
                    PrimaryCurrency = "IRR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IS",
                    PrimaryCurrency = "ISK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "IT",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "JE",
                    PrimaryCurrency = "GBP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "JM",
                    PrimaryCurrency = "JMD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "JO",
                    PrimaryCurrency = "JOD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "JP",
                    PrimaryCurrency = "JPY",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KE",
                    PrimaryCurrency = "KES",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KG",
                    PrimaryCurrency = "KGS",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KH",
                    PrimaryCurrency = "KHR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KI",
                    PrimaryCurrency = "AUD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KM",
                    PrimaryCurrency = "KMF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KN",
                    PrimaryCurrency = "XCD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KP",
                    PrimaryCurrency = "KPW",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KR",
                    PrimaryCurrency = "KRW",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KW",
                    PrimaryCurrency = "KWD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KY",
                    PrimaryCurrency = "KYD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "KZ",
                    PrimaryCurrency = "KZT",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LA",
                    PrimaryCurrency = "LAK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LB",
                    PrimaryCurrency = "LBP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LC",
                    PrimaryCurrency = "XCD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LI",
                    PrimaryCurrency = "CHF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LK",
                    PrimaryCurrency = "LKR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LR",
                    PrimaryCurrency = "LRD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LS",
                    PrimaryCurrency = "ZAR",
                    SecondaryCurrencies = new []
                    {
                        "LSL",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LT",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LU",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LV",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "LY",
                    PrimaryCurrency = "LYD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MA",
                    PrimaryCurrency = "MAD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MC",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MD",
                    PrimaryCurrency = "MDL",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ME",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MF",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MG",
                    PrimaryCurrency = "MGA",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MH",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MK",
                    PrimaryCurrency = "MKD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ML",
                    PrimaryCurrency = "XOF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MM",
                    PrimaryCurrency = "MMK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MN",
                    PrimaryCurrency = "MNT",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MO",
                    PrimaryCurrency = "MOP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MP",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MQ",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MR",
                    PrimaryCurrency = "MRU",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MS",
                    PrimaryCurrency = "XCD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MT",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MU",
                    PrimaryCurrency = "MUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MV",
                    PrimaryCurrency = "MVR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MW",
                    PrimaryCurrency = "MWK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MX",
                    PrimaryCurrency = "MXN",
                    SecondaryCurrencies = new []
                    {
                        "MXV",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MY",
                    PrimaryCurrency = "MYR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "MZ",
                    PrimaryCurrency = "MZN",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NA",
                    PrimaryCurrency = "NAD",
                    SecondaryCurrencies = new []
                    {
                        "ZAR",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NC",
                    PrimaryCurrency = "XPF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NE",
                    PrimaryCurrency = "XOF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NF",
                    PrimaryCurrency = "AUD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NG",
                    PrimaryCurrency = "NGN",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NI",
                    PrimaryCurrency = "NIO",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NL",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NO",
                    PrimaryCurrency = "NOK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NP",
                    PrimaryCurrency = "NPR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NR",
                    PrimaryCurrency = "AUD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NU",
                    PrimaryCurrency = "NZD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "NZ",
                    PrimaryCurrency = "NZD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "OM",
                    PrimaryCurrency = "OMR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PA",
                    PrimaryCurrency = "PAB",
                    SecondaryCurrencies = new []
                    {
                        "USD",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PE",
                    PrimaryCurrency = "PEN",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PF",
                    PrimaryCurrency = "XPF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PG",
                    PrimaryCurrency = "PGK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PH",
                    PrimaryCurrency = "PHP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PK",
                    PrimaryCurrency = "PKR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PL",
                    PrimaryCurrency = "PLN",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PM",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PN",
                    PrimaryCurrency = "NZD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PR",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PS",
                    PrimaryCurrency = "ILS",
                    SecondaryCurrencies = new []
                    {
                        "JOD",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PT",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PW",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "PY",
                    PrimaryCurrency = "PYG",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "QA",
                    PrimaryCurrency = "QAR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "RE",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "RO",
                    PrimaryCurrency = "RON",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "RS",
                    PrimaryCurrency = "RSD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "RU",
                    PrimaryCurrency = "RUB",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "RW",
                    PrimaryCurrency = "RWF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SA",
                    PrimaryCurrency = "SAR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SB",
                    PrimaryCurrency = "SBD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SC",
                    PrimaryCurrency = "SCR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SD",
                    PrimaryCurrency = "SDG",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SE",
                    PrimaryCurrency = "SEK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SG",
                    PrimaryCurrency = "SGD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SH",
                    PrimaryCurrency = "SHP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SI",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SJ",
                    PrimaryCurrency = "NOK",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SK",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SL",
                    PrimaryCurrency = "SLE",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SM",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SN",
                    PrimaryCurrency = "XOF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SO",
                    PrimaryCurrency = "SOS",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SR",
                    PrimaryCurrency = "SRD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SS",
                    PrimaryCurrency = "SSP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ST",
                    PrimaryCurrency = "STN",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SV",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SX",
                    PrimaryCurrency = "XCG",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SY",
                    PrimaryCurrency = "SYP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "SZ",
                    PrimaryCurrency = "SZL",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TA",
                    PrimaryCurrency = "GBP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TC",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TD",
                    PrimaryCurrency = "XAF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TF",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TG",
                    PrimaryCurrency = "XOF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TH",
                    PrimaryCurrency = "THB",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TJ",
                    PrimaryCurrency = "TJS",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TK",
                    PrimaryCurrency = "NZD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TL",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TM",
                    PrimaryCurrency = "TMT",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TN",
                    PrimaryCurrency = "TND",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TO",
                    PrimaryCurrency = "TOP",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TR",
                    PrimaryCurrency = "TRY",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TT",
                    PrimaryCurrency = "TTD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TV",
                    PrimaryCurrency = "AUD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TW",
                    PrimaryCurrency = "TWD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "TZ",
                    PrimaryCurrency = "TZS",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "UA",
                    PrimaryCurrency = "UAH",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "UG",
                    PrimaryCurrency = "UGX",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "UM",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "US",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = new []
                    {
                        "USN",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "UY",
                    PrimaryCurrency = "UYU",
                    SecondaryCurrencies = new []
                    {
                        "UYI",
                        "UYW",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "UZ",
                    PrimaryCurrency = "UZS",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "VA",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "VC",
                    PrimaryCurrency = "XCD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "VE",
                    PrimaryCurrency = "VES",
                    SecondaryCurrencies = new []
                    {
                        "VED",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "VG",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "VI",
                    PrimaryCurrency = "USD",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "VN",
                    PrimaryCurrency = "VND",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "VU",
                    PrimaryCurrency = "VUV",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "WF",
                    PrimaryCurrency = "XPF",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "WS",
                    PrimaryCurrency = "WST",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "XK",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "YE",
                    PrimaryCurrency = "YER",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "YT",
                    PrimaryCurrency = "EUR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ZA",
                    PrimaryCurrency = "ZAR",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ZM",
                    PrimaryCurrency = "ZMW",
                    SecondaryCurrencies = []
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ZW",
                    PrimaryCurrency = "ZWG",
                    SecondaryCurrencies = new []
                    {
                        "USD",
                    }
               },
               new CountryCurrencyInfoRow()
               {
                    CountryCode = "ZZ",
                    PrimaryCurrency = "XAD",
                    SecondaryCurrencies = new []
                    {
                        "XAG",
                        "XAU",
                        "XBA",
                        "XBB",
                        "XBC",
                        "XBD",
                        "XDR",
                        "XPD",
                        "XPT",
                        "XSU",
                        "XTS",
                        "XUA",
                        "XXX",
                    }
               },
         });
      private static readonly ImmutableArray<CountryCurrencyInfo> Data;
      private static readonly Dictionary<CountryCode.TwoLetterCode, CountryCurrencyInfo> Index;

      /// <summary>
      /// Attempts to get currency information for a country.
      /// </summary>
      public static bool TryGet(CountryCode.TwoLetterCode country,out CountryCurrencyInfo? info) => Index.TryGetValue(country, out info);

      static CountryCurrencyMap()
      {
         var dataBuilder = ImmutableArray.CreateBuilder<CountryCurrencyInfo>(RawData.Length);
         var index = new Dictionary<CountryCode.TwoLetterCode, CountryCurrencyInfo>(RawData.Length);

         foreach (var row in RawData)
         {
            if (!Enum.TryParse(row.CountryCode, out CountryCode.TwoLetterCode country))
               continue;
            if (!Enum.TryParse(row.PrimaryCurrency, out CurrencyCode primary))
               continue;

            var info = new CountryCurrencyInfo
            {
               CountryCode = country,
               PrimaryCurrency = primary,
               SecondaryCurrencies = FilterSecondary(row.SecondaryCurrencies)
            };

            dataBuilder.Add(info);
            index[country] = info;
         }

         Data = dataBuilder.ToImmutable();
         Index = index;
      }

      private static IReadOnlyList<CurrencyCode> FilterSecondary(IReadOnlyList<string> values)
      {
         if (values.Count == 0)
            return Array.Empty<CurrencyCode>();

         var buffer = new CurrencyCode[values.Count];
         var count = 0;

         foreach (var value in values)
         {
            if (Enum.TryParse(value, out CurrencyCode code))
               buffer[count++] = code;
         }

         if (count == 0)
            return Array.Empty<CurrencyCode>();

         if (count == buffer.Length)
            return buffer;

         var result = new CurrencyCode[count];
         Array.Copy(buffer, result, count);
         return result;
      }
    }
}
